require 'jquery/mark_it_up'

ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup              => ['jquery.markitup.min']

ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_preview => ['compiled/jquery/markitup/templates/preview.css']

ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_default   => ['compiled/jquery/markitup/sets/default.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_bbcode    => ['compiled/jquery/markitup/sets/bbcode.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_xbbcode   => ['compiled/jquery/markitup/sets/xbbcode.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_css       => ['compiled/jquery/markitup/sets/css.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_dotclear  => ['compiled/jquery/markitup/sets/dotclear.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_html      => ['compiled/jquery/markitup/sets/html.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_markdown  => ['compiled/jquery/markitup/sets/markdown.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_markmin   => ['compiled/jquery/markitup/sets/markmin.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_rest      => ['compiled/jquery/markitup/sets/rest.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_textile   => ['compiled/jquery/markitup/sets/textile.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_texy      => ['compiled/jquery/markitup/sets/texy.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_txt2tags  => ['compiled/jquery/markitup/sets/txt2tags.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_set_wiki      => ['compiled/jquery/markitup/sets/wiki.css']

ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_default  => ['markitup/jquery.markitup.set.default.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_bbcode   => ['markitup/jquery.markitup.set.bbcode.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_xbbcode  => ['markitup/jquery.markitup.set.xbbcode.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_css      => ['markitup/jquery.markitup.set.css.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_dotclear => ['markitup/jquery.markitup.set.dotclear.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_html     => ['markitup/jquery.markitup.set.html.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_markdown => ['markitup/jquery.markitup.set.markdown.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_markmin  => ['markitup/jquery.markitup.set.markmin.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_rest     => ['markitup/jquery.markitup.set.rest.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_textile  => ['markitup/jquery.markitup.set.textile.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_texy     => ['markitup/jquery.markitup.set.texy.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_txt2tags => ['markitup/jquery.markitup.set.txt2tags.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_set_wiki     => ['markitup/jquery.markitup.set.wiki.min']

ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_skin_markitup => ['compiled/jquery/markitup/skins/markitup.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_skin_aqua     => ['compiled/jquery/markitup/skins/aqua.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_skin_jtag     => ['compiled/jquery/markitup/skins/jtageditor.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_skin_live     => ['compiled/jquery/markitup/skins/live.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_skin_simple   => ['compiled/jquery/markitup/skins/simple.css']
