require 'jquery/mark_it_up'

ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup        => ['compiled/jquery/markitup/skins/markitup.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_aqua   => ['compiled/jquery/markitup/skins/aqua.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_jtag   => ['compiled/jquery/markitup/skins/jtageditor.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_live   => ['compiled/jquery/markitup/skins/live.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_simple => ['compiled/jquery/markitup/skins/simple.css']

ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_default  => ['compiled/jquery/markitup/sets/default.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_bbcode   => ['compiled/jquery/markitup/sets/bbcode.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_dotclear => ['compiled/jquery/markitup/sets/dotclear.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_html     => ['compiled/jquery/markitup/sets/html.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_markdown => ['compiled/jquery/markitup/sets/markdown.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_textile  => ['compiled/jquery/markitup/sets/textile.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_wiki     => ['compiled/jquery/markitup/sets/wiki.css']

ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_preview => ['compiled/jquery/markitup/templates/preview.css']

ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup          => ['jquery.markitup.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_default  => ['markitup/jquery.markitup.set.default.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_bbcode   => ['markitup/jquery.markitup.set.bbcode.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_xbbcode  => ['markitup/jquery.markitup.set.xbbcode.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_css      => ['markitup/jquery.markitup.set.css.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_dotclear => ['markitup/jquery.markitup.set.dotclear.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_html     => ['markitup/jquery.markitup.set.html.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_markdown => ['markitup/jquery.markitup.set.markdown.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_markmin  => ['markitup/jquery.markitup.set.markmin.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_rest     => ['markitup/jquery.markitup.set.rest.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_textile  => ['markitup/jquery.markitup.set.textile.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_texy     => ['markitup/jquery.markitup.set.texy.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_txt2tags => ['markitup/jquery.markitup.set.txt2tags.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_wiki     => ['markitup/jquery.markitup.set.wiki.min']
