tinyMCEPopup.requireLangPack();
function initCommonAttributes(a){var b=document.forms[0],c=tinyMCEPopup.editor.dom;setFormValue("title",c.getAttrib(a,"title"));setFormValue("id",c.getAttrib(a,"id"));selectByValue(b,"class",c.getAttrib(a,"class"),true);setFormValue("style",c.getAttrib(a,"style"));selectByValue(b,"dir",c.getAttrib(a,"dir"));setFormValue("lang",c.getAttrib(a,"lang"));setFormValue("onfocus",c.getAttrib(a,"onfocus"));setFormValue("onblur",c.getAttrib(a,"onblur"));setFormValue("onclick",c.getAttrib(a,"onclick"));setFormValue("ondblclick",
c.getAttrib(a,"ondblclick"));setFormValue("onmousedown",c.getAttrib(a,"onmousedown"));setFormValue("onmouseup",c.getAttrib(a,"onmouseup"));setFormValue("onmouseover",c.getAttrib(a,"onmouseover"));setFormValue("onmousemove",c.getAttrib(a,"onmousemove"));setFormValue("onmouseout",c.getAttrib(a,"onmouseout"));setFormValue("onkeypress",c.getAttrib(a,"onkeypress"));setFormValue("onkeydown",c.getAttrib(a,"onkeydown"));setFormValue("onkeyup",c.getAttrib(a,"onkeyup"))}
function setFormValue(a,b){if(document.forms[0].elements[a])document.forms[0].elements[a].value=b}function insertDateTime(a){document.getElementById(a).value=getDateTime(new Date,"%Y-%m-%dT%H:%M:%S")}
function getDateTime(a,b){b=b.replace("%D","%m/%d/%y");b=b.replace("%r","%I:%M:%S %p");b=b.replace("%Y",""+a.getFullYear());b=b.replace("%y",""+a.getYear());b=b.replace("%m",addZeros(a.getMonth()+1,2));b=b.replace("%d",addZeros(a.getDate(),2));b=b.replace("%H",""+addZeros(a.getHours(),2));b=b.replace("%M",""+addZeros(a.getMinutes(),2));b=b.replace("%S",""+addZeros(a.getSeconds(),2));b=b.replace("%I",""+((a.getHours()+11)%12+1));b=b.replace("%p",""+(a.getHours()<12?"AM":"PM"));return b=b.replace("%%",
"%")}function addZeros(a,b){var c;a=""+a;if(a.length<b)for(c=0;c<b-a.length;c++)a="0"+a;return a}function selectByValue(a,b,c,d,f){if(a&&a.elements[b]){a=a.elements[b];b=false;for(var g=0;g<a.options.length;g++){var e=a.options[g];if(e.value==c||f&&e.value.toLowerCase()==c.toLowerCase())b=e.selected=true;else e.selected=false}if(!b&&d&&c!=""){e=new Option("Value: "+c,c);e.selected=true;a.options[a.options.length]=e}return b}}
function setAttrib(a,b,c){var d=document.forms[0].elements[b.toLowerCase()];tinyMCEPopup.editor.dom.setAttrib(a,b,c||d.value)}function setAllCommonAttribs(a){setAttrib(a,"title");setAttrib(a,"id");setAttrib(a,"class");setAttrib(a,"style");setAttrib(a,"dir");setAttrib(a,"lang")}SXE={currentAction:"insert",inst:tinyMCEPopup.editor,updateElement:null};SXE.focusElement=SXE.inst.selection.getNode();
SXE.initElementDialog=function(a){addClassesToList("class","xhtmlxtras_styles");TinyMCE_EditableSelects.init();a=a.toLowerCase();var b=SXE.inst.dom.getParent(SXE.focusElement,a.toUpperCase());if(b!=null&&b.nodeName.toUpperCase()==a.toUpperCase())SXE.currentAction="update";if(SXE.currentAction=="update"){initCommonAttributes(b);SXE.updateElement=b}document.forms[0].insert.value=tinyMCEPopup.getLang(SXE.currentAction,"Insert",true)};
SXE.insertElement=function(a){var b=SXE.inst.dom.getParent(SXE.focusElement,a.toUpperCase());if(b==null){if(SXE.inst.selection.getContent().length>0){insertInlineElement(a);a=tinymce.grep(SXE.inst.dom.select(a));for(var c=0;c<a.length;c++){b=a[c];if(SXE.inst.dom.getAttrib(b,"data-mce-new")){b.id="";b.setAttribute("id","");b.removeAttribute("id");b.removeAttribute("data-mce-new");setAllCommonAttribs(b)}}}}else setAllCommonAttribs(b);SXE.inst.nodeChanged();tinyMCEPopup.execCommand("mceEndUndoLevel")};
SXE.removeElement=function(a){a=a.toLowerCase();if((elm=SXE.inst.dom.getParent(SXE.focusElement,a.toUpperCase()))&&elm.nodeName.toUpperCase()==a.toUpperCase()){tinyMCE.execCommand("mceRemoveNode",false,elm);SXE.inst.nodeChanged();tinyMCEPopup.execCommand("mceEndUndoLevel")}};SXE.showRemoveButton=function(){document.getElementById("remove").style.display=""};SXE.containsClass=function(a,b){return a.className.indexOf(b)>-1?true:false};
SXE.removeClass=function(a,b){if(a.className==null||a.className==""||!SXE.containsClass(a,b))return true;for(var c=a.className.split(" "),d="",f=0,g=c.length;f<g;f++)if(c[f]!=b)d+=c[f]+" ";a.className=d.substring(0,d.length-1)};SXE.addClass=function(a,b){if(!SXE.containsClass(a,b))a.className?a.className+=" "+b:a.className=b;return true};
function insertInlineElement(a){var b=tinyMCEPopup.editor,c=b.dom;b.getDoc().execCommand("FontName",false,"mceinline");tinymce.each(c.select("span,font"),function(d){if(d.style.fontFamily=="mceinline"||d.face=="mceinline")c.replace(c.create(a,{"data-mce-new":1}),d,1)})};
