# Generated by compass-jquery-plugin/gem-tasks/calendar.rake
# Install with: compass -f jquery -p calendar

file 'config/initializers/calendar.rb'
javascript 'jquery.calendar.js'
javascript 'jquery.calendar.min.js'
stylesheet 'jquery.ui/calendar.sass'
