require 'fileutils'
require 'lib/handle_js_files'

# Compass generator for jquery.mobile 3.5+
JQMOBILE_SRC = File.join(GEM_ROOT, 'src', 'jquery.mobile')
JQMOBILE_SRC_STYLESHEETS = File.join(JQMOBILE_SRC, 'css')
JQMOBILE_SRC_IMAGES = File.join(JQMOBILE_SRC, 'images')
JQMOBILE_SRC_THEMES = File.join(JQMOBILE_SRC, 'themes')

JQMOBILE_DEST_TEMPLATES = File.join(GEM_ROOT, 'templates', 'jqmobile')
JQMOBILE_DEST_STYLESHEETS = File.join(JQMOBILE_DEST_TEMPLATES, 'jquery.mobile')
JQMOBILE_DEST_THEMES = File.join(JQMOBILE_DEST_TEMPLATES, 'jquery.mobile')
JQMOBILE_DEST_IMAGES = File.join(JQMOBILE_DEST_STYLESHEETS)

JQMOBILE_MESSAGE1 = "# Generated by compass-jquery-plugin/gem-tasks/jquery.mobile.rake\n# Install with: compass install jquery/jquery.mobile\n\n"
JQMOBILE_MESSAGE2 = "// Generated by compass-jquery-plugin/gem-tasks/jquery.mobile.rake\n\n"

all_scripts = [
  'js/jquery.mobile-1.0a1.js',
  'js/jquery.mobile.themeswitcher.js'
].collect {|filename| File.read(File.join(JQMOBILE_SRC, filename))}.join "\n\n"

all_stylesheets = [
  'css/jquery.mobile-1.0a1.css'  
].collect {|filename| File.read(File.join(JQMOBILE_SRC, filename))}.join "\n\n"

namespace :build do
  desc 'Build the stylesheets and templates for jquery.mobile.'
  task :jqmobile do    
    
    FileUtils.remove_dir JQMOBILE_DEST_TEMPLATES if File.exists? JQMOBILE_DEST_TEMPLATES 
    FileUtils.mkdir_p(File.join(JQMOBILE_DEST_TEMPLATES, 'config', 'initializers'))
    
    open File.join(JQMOBILE_DEST_TEMPLATES, 'manifest.rb'), 'w' do |manifest|
      manifest.print JQMOBILE_MESSAGE1
      
      open File.join(JQMOBILE_DEST_TEMPLATES, 'config', 'initializers', 'jqmobile.rb'), 'w' do |f|
        f.print(File.read(File.join(JQMOBILE_SRC, 'config', 'initializers', 'jqmobile.rb')))
      end
      manifest.print "file 'config/initializers/jqmobile.rb'\n"  
    
      #JavaScripts
    
      open File.join(JQMOBILE_DEST_TEMPLATES, 'jquery.mobile.js'), 'w' do |f|
        f.print concat_files(all_scripts)
      end
      manifest.print "javascript 'jquery.mobile.js'\n"
    
      open File.join(JQMOBILE_DEST_TEMPLATES, 'jquery.mobile.min.js'), 'w' do |f|
        f.print compress_js(all_scripts, "yui")
      end
      manifest.print "javascript 'jquery.mobile.min.js'\n"
      
#      # Stylesheets
#      FileUtils.mkdir_p(JQMOBILE_DEST_STYLESHEETS)
#      
#      open File.join(JQMOBILE_DEST_STYLESHEETS, 'jquery.mobile.scss'), 'w' do |f|
#        sass = JQMOBILE_MESSAGE2 
#        IO.popen("sass-convert -F css -T scss", 'r+') { |ff| ff.print(all_stylesheets); ff.close_write; sass += ff.read }
#        f.print sass
#      end
#      manifest.print "stylesheet 'jquery.mobile/jquery.mobile.scss'\n"
              
      # jQuery Mobile Themes

      FileUtils.mkdir_p(JQMOBILE_DEST_THEMES)
      
      Dir.foreach JQMOBILE_SRC_THEMES do |theme|
        next if /^\./ =~ theme
    
        # Convert the stylesheets      
        Dir.foreach File.join(JQMOBILE_SRC_THEMES, "#{theme}") do |file|
          next unless /\.css$/ =~ file
          css = File.read File.join(JQMOBILE_SRC_THEMES, "#{theme}", file)
          sass = ''
          IO.popen("sass-convert -F css -T scss", 'r+') { |f| f.print(css); f.close_write; sass = f.read }
          open File.join(JQMOBILE_DEST_THEMES, "jqm.#{theme}.scss"), 'w' do |f|
            f.write JQMOBILE_MESSAGE2 + sass
          end
          manifest.print "stylesheet 'jquery.mobile/jqm.#{theme}.scss', :media => 'screen, projection'\n"
        end

        # Copy the theme images directory
        src_dir = File.join(JQMOBILE_SRC_THEMES, theme, 'images')
        dest_dir = File.join(JQMOBILE_DEST_IMAGES, "#{theme}")
        FileUtils.mkdir_p dest_dir
        
        Dir.foreach(src_dir) do |image|
          next if /^\./ =~ image
          FileUtils.cp(File.join(src_dir, image), dest_dir)    
          manifest.print "image 'jquery.mobile/#{theme}/#{image}'\n"
        end
      end     
    end
  end
end