require 'fileutils'
require 'lib/handle_js_files'

# Compass generator for jqtools 3.5+
JQTOOLS_SRC = File.join(GEM_ROOT, 'src', 'jqtools')

JQTOOLS_DEST_TEMPLATES = File.join(GEM_ROOT, 'templates', 'jqtools')

JQTOOLS_MESSAGE1 = "# Generated by compass-jquery-plugin/gem-tasks/jqtools.rake\n# Install with: compass install jquery/jqtools\n\n"
JQTOOLS_MESSAGE2 = "// Generated by compass-jquery-plugin/gem-tasks/jqtools.rake\n\n"

all_scripts = [
  'js/dateinput.js',
  'js/overlay.js',
  'js/overlay.apple.js',
  'js/rangeinput.js',
  'js/scrollable.js',
  'js/scrollable.autoscroll.js',
  'js/scrollable.navigator.js',
  'js/tabs.js',
  'js/tabs.slideshow.js',
  'js/toolbox.expose.js',
  'js/toolbox.flashembed.js',
  'js/toolbox.history.js',
  'js/toolbox.mousewheel.js',
  'js/tooltip.js',
  'js/tooltip.dynamic.js',
  'js/tooltip.slide.js',
  'js/validator.js'
].collect {|filename| File.read(File.join(JQTOOLS_SRC, filename))}.join "\n\n"

namespace :build do
  desc 'Build the stylesheets and templates for jqtools.'
  task :jqtools do    
    
    FileUtils.remove_dir JQTOOLS_DEST_TEMPLATES if File.exists? JQTOOLS_DEST_TEMPLATES 
    FileUtils.mkdir_p(File.join(JQTOOLS_DEST_TEMPLATES, 'config', 'initializers'))
    
    open File.join(JQTOOLS_DEST_TEMPLATES, 'manifest.rb'), 'w' do |manifest|
      manifest.print JQTOOLS_MESSAGE1
      
      open File.join(JQTOOLS_DEST_TEMPLATES, 'config', 'initializers', 'jqtools.rb'), 'w' do |f|
        f.print(File.read(File.join(JQTOOLS_SRC, 'config', 'initializers', 'jqtools.rb')))
      end
      manifest.print "file 'config/initializers/jqtools.rb'\n"  
    
      #JavaScripts
    
      open File.join(JQTOOLS_DEST_TEMPLATES, 'jquery.tools.js'), 'w' do |f|
        f.print concat_files(all_scripts)
      end
      manifest.print "javascript 'jquery.tools.js'\n"
    
      open File.join(JQTOOLS_DEST_TEMPLATES, 'jquery.tools.min.js'), 'w' do |f|
        f.print compress_js(all_scripts, "google")
      end
      manifest.print "javascript 'jquery.tools.min.js'\n"
    end
  end
end