tinyMCEPopup.requireLangPack();var templates={"window.open":"window.open('${url}','${target}','${options}')"};function preinit(){var a;if(a=tinyMCEPopup.getParam("external_link_list_url"))document.write('<script language="javascript" type="text/javascript" src="'+tinyMCEPopup.editor.documentBaseURI.toAbsolute(a)+'"><\/script>')}function changeClass(){var a=document.forms[0];a.classes.value=getSelectValue(a,"classlist")}
function init(){tinyMCEPopup.resizeToInnerSize();var a=document.forms[0],b=tinyMCEPopup.editor,c=b.selection.getNode(),d="insert",e;document.getElementById("hrefbrowsercontainer").innerHTML=getBrowserHTML("hrefbrowser","href","file","advlink");document.getElementById("popupurlbrowsercontainer").innerHTML=getBrowserHTML("popupurlbrowser","popupurl","file","advlink");document.getElementById("linklisthrefcontainer").innerHTML=getLinkListHTML("linklisthref","href");document.getElementById("anchorlistcontainer").innerHTML=
getAnchorListHTML("anchorlist","href");document.getElementById("targetlistcontainer").innerHTML=getTargetListHTML("targetlist","target");e=getLinkListHTML("linklisthref","href");if(e=="")document.getElementById("linklisthrefrow").style.display="none";else document.getElementById("linklisthrefcontainer").innerHTML=e;if(isVisible("hrefbrowser"))document.getElementById("href").style.width="260px";if(isVisible("popupurlbrowser"))document.getElementById("popupurl").style.width="180px";c=b.dom.getParent(c,
"A");if(c!=null&&c.nodeName=="A")d="update";a.insert.value=tinyMCEPopup.getLang(d,"Insert",true);setPopupControlsDisabled(true);if(d=="update"){d=b.dom.getAttrib(c,"href");e=b.dom.getAttrib(c,"onclick");setFormValue("href",d);setFormValue("title",b.dom.getAttrib(c,"title"));setFormValue("id",b.dom.getAttrib(c,"id"));setFormValue("style",b.dom.getAttrib(c,"style"));setFormValue("rel",b.dom.getAttrib(c,"rel"));setFormValue("rev",b.dom.getAttrib(c,"rev"));setFormValue("charset",b.dom.getAttrib(c,"charset"));
setFormValue("hreflang",b.dom.getAttrib(c,"hreflang"));setFormValue("dir",b.dom.getAttrib(c,"dir"));setFormValue("lang",b.dom.getAttrib(c,"lang"));setFormValue("tabindex",b.dom.getAttrib(c,"tabindex",typeof c.tabindex!="undefined"?c.tabindex:""));setFormValue("accesskey",b.dom.getAttrib(c,"accesskey",typeof c.accesskey!="undefined"?c.accesskey:""));setFormValue("type",b.dom.getAttrib(c,"type"));setFormValue("onfocus",b.dom.getAttrib(c,"onfocus"));setFormValue("onblur",b.dom.getAttrib(c,"onblur"));
setFormValue("onclick",e);setFormValue("ondblclick",b.dom.getAttrib(c,"ondblclick"));setFormValue("onmousedown",b.dom.getAttrib(c,"onmousedown"));setFormValue("onmouseup",b.dom.getAttrib(c,"onmouseup"));setFormValue("onmouseover",b.dom.getAttrib(c,"onmouseover"));setFormValue("onmousemove",b.dom.getAttrib(c,"onmousemove"));setFormValue("onmouseout",b.dom.getAttrib(c,"onmouseout"));setFormValue("onkeypress",b.dom.getAttrib(c,"onkeypress"));setFormValue("onkeydown",b.dom.getAttrib(c,"onkeydown"));setFormValue("onkeyup",
b.dom.getAttrib(c,"onkeyup"));setFormValue("target",b.dom.getAttrib(c,"target"));setFormValue("classes",b.dom.getAttrib(c,"class"));e!=null&&e.indexOf("window.open")!=-1?parseWindowOpen(e):parseFunction(e);selectByValue(a,"dir",b.dom.getAttrib(c,"dir"));selectByValue(a,"rel",b.dom.getAttrib(c,"rel"));selectByValue(a,"rev",b.dom.getAttrib(c,"rev"));selectByValue(a,"linklisthref",d);d.charAt(0)=="#"&&selectByValue(a,"anchorlist",d);addClassesToList("classlist","advlink_styles");selectByValue(a,"classlist",
b.dom.getAttrib(c,"class"),true);selectByValue(a,"targetlist",b.dom.getAttrib(c,"target"),true)}else addClassesToList("classlist","advlink_styles")}function checkPrefix(a){if(a.value&&Validator.isEmail(a)&&!/^\s*mailto:/i.test(a.value)&&confirm(tinyMCEPopup.getLang("advlink_dlg.is_email")))a.value="mailto:"+a.value;if(/^\s*www\./i.test(a.value)&&confirm(tinyMCEPopup.getLang("advlink_dlg.is_external")))a.value="http://"+a.value}function setFormValue(a,b){document.forms[0].elements[a].value=b}
function parseWindowOpen(a){var b=document.forms[0];if(a.indexOf("return false;")!=-1){b.popupreturn.checked=true;a=a.replace("return false;","")}else b.popupreturn.checked=false;a=parseLink(a);if(a!=null){b.ispopup.checked=true;setPopupControlsDisabled(false);var c=parseOptions(a.options),d=a.url;b.popupname.value=a.target;b.popupurl.value=d;b.popupwidth.value=getOption(c,"width");b.popupheight.value=getOption(c,"height");b.popupleft.value=getOption(c,"left");b.popuptop.value=getOption(c,"top");
if(b.popupleft.value.indexOf("screen")!=-1)b.popupleft.value="c";if(b.popuptop.value.indexOf("screen")!=-1)b.popuptop.value="c";b.popuplocation.checked=getOption(c,"location")=="yes";b.popupscrollbars.checked=getOption(c,"scrollbars")=="yes";b.popupmenubar.checked=getOption(c,"menubar")=="yes";b.popupresizable.checked=getOption(c,"resizable")=="yes";b.popuptoolbar.checked=getOption(c,"toolbar")=="yes";b.popupstatus.checked=getOption(c,"status")=="yes";b.popupdependent.checked=getOption(c,"dependent")==
"yes";buildOnClick()}}function parseFunction(a){parseLink(a)}function getOption(a,b){return typeof a[b]=="undefined"?"":a[b]}
function setPopupControlsDisabled(a){var b=document.forms[0];b.popupname.disabled=a;b.popupurl.disabled=a;b.popupwidth.disabled=a;b.popupheight.disabled=a;b.popupleft.disabled=a;b.popuptop.disabled=a;b.popuplocation.disabled=a;b.popupscrollbars.disabled=a;b.popupmenubar.disabled=a;b.popupresizable.disabled=a;b.popuptoolbar.disabled=a;b.popupstatus.disabled=a;b.popupreturn.disabled=a;b.popupdependent.disabled=a;setBrowserDisabled("popupurlbrowser",a)}
function parseLink(a){a=a.replace(RegExp("&#39;","g"),"'");var b=a.replace(RegExp("\\s*([A-Za-z0-9.]*)\\s*\\(.*","gi"),"$1"),c=templates[b];if(c){c=c.match(RegExp("'?\\$\\{[A-Za-z0-9.]*\\}'?","gi"));for(var d="\\s*[A-Za-z0-9.]*\\s*\\(",e="",f=0;f<c.length;f++){d+=c[f].indexOf("'${")!=-1?"'(.*)'":"([0-9]*)";e+="$"+(f+1);c[f]=c[f].replace(RegExp("[^A-Za-z0-9]","gi"),"");if(f!=c.length-1){d+="\\s*,\\s*";e+="<delim>"}else d+=".*"}d+="\\);?";var g=[];g._function=b;a=a.replace(RegExp(d,"gi"),e).split("<delim>");
for(f=0;f<c.length;f++)g[c[f]]=a[f];return g}return null}function parseOptions(a){if(a==null||a=="")return[];a=a.toLowerCase();a=a.replace(/;/g,",");a=a.replace(/[^0-9a-z=,]/g,"");a=a.split(",");for(var b=[],c=0;c<a.length;c++){var d=a[c].split("=");if(d.length==2)b[d[0]]=d[1]}return b}
function buildOnClick(){var a=document.forms[0];if(a.ispopup.checked){var b="window.open('",c=a.popupurl.value;b+=c+"','";b+=a.popupname.value+"','";if(a.popuplocation.checked)b+="location=yes,";if(a.popupscrollbars.checked)b+="scrollbars=yes,";if(a.popupmenubar.checked)b+="menubar=yes,";if(a.popupresizable.checked)b+="resizable=yes,";if(a.popuptoolbar.checked)b+="toolbar=yes,";if(a.popupstatus.checked)b+="status=yes,";if(a.popupdependent.checked)b+="dependent=yes,";if(a.popupwidth.value!="")b+="width="+
a.popupwidth.value+",";if(a.popupheight.value!="")b+="height="+a.popupheight.value+",";if(a.popupleft.value!="")b+=a.popupleft.value!="c"?"left="+a.popupleft.value+",":"left='+(screen.availWidth/2-"+a.popupwidth.value/2+")+',";if(a.popuptop.value!="")b+=a.popuptop.value!="c"?"top="+a.popuptop.value+",":"top='+(screen.availHeight/2-"+a.popupheight.value/2+")+',";if(b.charAt(b.length-1)==",")b=b.substring(0,b.length-1);b+="');";if(a.popupreturn.checked)b+="return false;";a.onclick.value=b;if(a.href.value==
"")a.href.value=c}else a.onclick.value=""}function setAttrib(a,b,c){var d=document.forms[0].elements[b.toLowerCase()],e=tinyMCEPopup.editor.dom;if(typeof c=="undefined"||c==null){c="";if(d)c=d.value}if(b=="style")c=e.serializeStyle(e.parseStyle(c),"a");e.setAttrib(a,b,c)}
function getAnchorListHTML(a,b){var c=tinyMCEPopup.editor,d=c.dom.select("a.mceItemAnchor,img.mceItemAnchor"),e,f,g="";g+='<select id="'+a+'" name="'+a+'" class="mceAnchorList" o2nfocus="tinyMCE.addSelectAccessibility(event, this, window);" onchange="this.form.'+b+".value=";g+='this.options[this.selectedIndex].value;">';g+='<option value="">---</option>';for(f=0;f<d.length;f++)if((e=c.dom.getAttrib(d[f],"name"))!="")g+='<option value="#'+e+'">'+e+"</option>";g+="</select>";return g}
function insertAction(){var a=tinyMCEPopup.editor,b,c,d;b=a.selection.getNode();checkPrefix(document.forms[0].href);b=a.dom.getParent(b,"A");if(document.forms[0].href.value){if(b==null){a.getDoc().execCommand("unlink",false,null);tinyMCEPopup.execCommand("mceInsertLink",false,"#mce_temp_url#",{skip_undo:1});c=tinymce.grep(a.dom.select("a"),function(e){return a.dom.getAttrib(e,"href")=="#mce_temp_url#"});for(d=0;d<c.length;d++)setAllAttribs(b=c[d])}else setAllAttribs(b);if(b.childNodes.length!=1||
b.firstChild.nodeName!="IMG"){a.focus();a.selection.select(b);a.selection.collapse(0);tinyMCEPopup.storeSelection()}}else{d=a.selection.getBookmark();a.dom.remove(b,1);a.selection.moveToBookmark(d)}tinyMCEPopup.execCommand("mceEndUndoLevel");tinyMCEPopup.close()}
function setAllAttribs(a){var b=document.forms[0],c=b.href.value.replace(/ /g,"%20"),d=getSelectValue(b,"targetlist");setAttrib(a,"href",c);setAttrib(a,"title");setAttrib(a,"target",d=="_self"?"":d);setAttrib(a,"id");setAttrib(a,"style");setAttrib(a,"class",getSelectValue(b,"classlist"));setAttrib(a,"rel");setAttrib(a,"rev");setAttrib(a,"charset");setAttrib(a,"hreflang");setAttrib(a,"dir");setAttrib(a,"lang");setAttrib(a,"tabindex");setAttrib(a,"accesskey");setAttrib(a,"type");setAttrib(a,"onfocus");
setAttrib(a,"onblur");setAttrib(a,"onclick");setAttrib(a,"ondblclick");setAttrib(a,"onmousedown");setAttrib(a,"onmouseup");setAttrib(a,"onmouseover");setAttrib(a,"onmousemove");setAttrib(a,"onmouseout");setAttrib(a,"onkeypress");setAttrib(a,"onkeydown");setAttrib(a,"onkeyup");if(tinyMCE.isMSIE5)a.outerHTML=a.outerHTML}function getSelectValue(a,b){var c=a.elements[b];if(!c||c.options==null||c.selectedIndex==-1)return"";return c.options[c.selectedIndex].value}
function getLinkListHTML(a,b,c){if(typeof tinyMCELinkList=="undefined"||tinyMCELinkList.length==0)return"";var d="";d+='<select id="'+a+'" name="'+a+'"';d+=' class="mceLinkList" onfoc2us="tinyMCE.addSelectAccessibility(event, this, window);" onchange="this.form.'+b+".value=";d+="this.options[this.selectedIndex].value;";if(typeof c!="undefined")d+=c+"('"+b+"',this.options[this.selectedIndex].text,this.options[this.selectedIndex].value);";d+='"><option value="">---</option>';for(a=0;a<tinyMCELinkList.length;a++)d+=
'<option value="'+tinyMCELinkList[a][1]+'">'+tinyMCELinkList[a][0]+"</option>";d+="</select>";return d}
function getTargetListHTML(a,b){var c=tinyMCEPopup.getParam("theme_advanced_link_targets","").split(";"),d="";d+='<select id="'+a+'" name="'+a+'" onf2ocus="tinyMCE.addSelectAccessibility(event, this, window);" onchange="this.form.'+b+".value=";d+='this.options[this.selectedIndex].value;">';d+='<option value="_self">'+tinyMCEPopup.getLang("advlink_dlg.target_same")+"</option>";d+='<option value="_blank">'+tinyMCEPopup.getLang("advlink_dlg.target_blank")+" (_blank)</option>";d+='<option value="_parent">'+
tinyMCEPopup.getLang("advlink_dlg.target_parent")+" (_parent)</option>";d+='<option value="_top">'+tinyMCEPopup.getLang("advlink_dlg.target_top")+" (_top)</option>";for(var e=0;e<c.length;e++){var f,g;if(c[e]!=""){f=c[e].split("=")[0];g=c[e].split("=")[1];d+='<option value="'+f+'">'+g+" ("+f+")</option>"}}d+="</select>";return d}preinit();tinyMCEPopup.onInit.add(init);
