# Generated by compass-jquery-plugin/gem-tasks/graphics.rake
# Install with: compass install jquery/graphics

file 'config/initializers/graphics.rb'
javascript 'jquery.sparkline.js'
javascript 'jquery.sparkline.min.js'
javascript 'jquery.ganttView.js'
javascript 'jquery.ganttView.min.js'
stylesheet 'jquery/ganttView.scss'
javascript 'jquery.highcharts.js'
javascript 'jquery.highcharts.min.js'
javascript 'highcharts/dark-blue.js'
javascript 'highcharts/dark-blue.min.js'
javascript 'highcharts/dark-green.js'
javascript 'highcharts/dark-green.min.js'
javascript 'highcharts/gray.js'
javascript 'highcharts/gray.min.js'
javascript 'highcharts/grid.js'
javascript 'highcharts/grid.min.js'
