# Generated by compass-jquery-plugin/gem-tasks/graphics.rake
# Install with: compass install jquery/graphics

file 'config/initializers/graphics.rb'
javascript 'jquery.sparkline.js'
javascript 'jquery.sparkline.min.js'
javascript 'jquery.ganttView.js'
javascript 'jquery.ganttView.min.js'
stylesheet 'jquery/ganttView.scss'
