(function(){function c(b){return document.getElementById(b)}function h(b){b=c(b);if(b.nodeName=="SELECT")return b.options[b.selectedIndex].value;if(b.type=="checkbox")return b.checked;return b.value}function f(b,e){if(typeof e!="undefined"){var j=c(b);if(j.nodeName=="SELECT")selectByValue(document.forms[0],b,e);else if(j.type=="checkbox")j.checked=!!e;else j.value=e}}var s;if(s=tinyMCEPopup.getParam("media_external_list_url"))document.write('<script language="javascript" type="text/javascript" src="'+
tinyMCEPopup.editor.documentBaseURI.toAbsolute(s)+'"><\/script>');window.Media={init:function(){var b;this.editor=tinyMCEPopup.editor;c("filebrowsercontainer").innerHTML=getBrowserHTML("filebrowser","src","media","media");c("qtsrcfilebrowsercontainer").innerHTML=getBrowserHTML("qtsrcfilebrowser","quicktime_qtsrc","media","media");c("bgcolor_pickcontainer").innerHTML=getColorPickerHTML("bgcolor_pick","bgcolor");c("video_altsource1_filebrowser").innerHTML=getBrowserHTML("filebrowser_altsource1","video_altsource1",
"media","media");c("video_altsource2_filebrowser").innerHTML=getBrowserHTML("filebrowser_altsource2","video_altsource2","media","media");c("video_poster_filebrowser").innerHTML=getBrowserHTML("filebrowser_poster","video_poster","media","image");b=this.getMediaListHTML("medialist","src","media","media");if(b=="")c("linklistrow").style.display="none";else c("linklistcontainer").innerHTML=b;if(isVisible("filebrowser"))c("src").style.width="230px";if(isVisible("filebrowser_altsource1"))c("video_altsource1").style.width=
"220px";if(isVisible("filebrowser_altsource2"))c("video_altsource2").style.width="220px";if(isVisible("filebrowser_poster"))c("video_poster").style.width="220px";this.data=tinyMCEPopup.getWindowArg("data");this.dataToForm();this.preview()},insert:function(){var b=tinyMCEPopup.editor;this.formToData();b.execCommand("mceRepaint");tinyMCEPopup.restoreSelection();b.selection.setNode(b.plugins.media.dataToImg(this.data));tinyMCEPopup.close()},preview:function(){c("prev").innerHTML=this.editor.plugins.media.dataToHtml(this.data,
true)},moveStates:function(b,e){function j(g){var l={};g&&tinymce.each(g.split("&"),function(m){m=m.split("=");l[unescape(m[0])]=unescape(m[1])});return l}function o(g,l){var m,n,p,i,k;if(g==a.type||g=="global"){l=tinymce.explode(l);for(m=0;m<l.length;m++){n=l[m];p=g=="global"?n:g+"_"+n;if(g=="global")k=a;else if(g=="video"){k=a.video.attrs;if(!k&&!b)a.video.attrs=k={}}else k=a.params;if(k)if(b)f(p,k[n]);else{delete k[n];i=h(p);if(g=="video"&&i===true)i=n;if(q[p]){if(i!==q[p]){i=""+i;k[n]=i}}else if(i){i=
""+i;k[n]=i}}}}}var a=this.data,t=this.editor;a=this.data;var r=t.plugins.media,d,q;q={quicktime_autoplay:true,quicktime_controller:true,flash_play:true,flash_loop:true,flash_menu:true,windowsmedia_autostart:true,windowsmedia_enablecontextmenu:true,windowsmedia_invokeurls:true,realmedia_autogotourl:true,realmedia_imagestatus:true};if(!b){a.type=c("media_type").options[c("media_type").selectedIndex].value;a.width=h("width");a.height=h("height");d=h("src");if(e=="src"){d=d.replace(/^.*\.([^.]+)$/,"$1");
if(r=r.getType(d))a.type=r.name.toLowerCase();f("media_type",a.type)}if(a.type=="video"){if(!a.video.sources)a.video.sources=[];a.video.sources[0]={src:h("src")}}}c("video_options").style.display="none";c("flash_options").style.display="none";c("quicktime_options").style.display="none";c("shockwave_options").style.display="none";c("windowsmedia_options").style.display="none";c("realmedia_options").style.display="none";if(c(a.type+"_options"))c(a.type+"_options").style.display="block";f("media_type",
a.type);o("flash","play,loop,menu,swliveconnect,quality,scale,salign,wmode,base,flashvars");o("quicktime","loop,autoplay,cache,controller,correction,enablejavascript,kioskmode,autohref,playeveryframe,targetcache,scale,starttime,endtime,target,qtsrcchokespeed,volume,qtsrc");o("shockwave","sound,progress,autostart,swliveconnect,swvolume,swstretchstyle,swstretchhalign,swstretchvalign");o("windowsmedia","autostart,enabled,enablecontextmenu,fullscreen,invokeurls,mute,stretchtofit,windowlessvideo,balance,baseurl,captioningid,currentmarker,currentposition,defaultframe,playcount,rate,uimode,volume");
o("realmedia","autostart,loop,autogotourl,center,imagestatus,maintainaspect,nojava,prefetch,shuffle,console,controls,numloop,scriptcallbacks");o("video","poster,autoplay,loop,preload,controls");o("global","id,name,vspace,hspace,bgcolor,align,width,height");if(b)if(a.type=="video"){a.video.sources[0]&&f("src",a.video.sources[0].src);(d=a.video.sources[1])&&f("video_altsource1",d.src);(d=a.video.sources[2])&&f("video_altsource2",d.src)}else{a.type=="flash"&&tinymce.each(t.getParam("flash_video_player_flashvars",
{url:"$url",poster:"$poster"}),function(g,l){if(g=="$url")a.params.src=j(a.params.flashvars)[l]||a.params.src});f("src",a.params.src)}else{d=h("src");if(d.match(/youtube.com(.+)v=([^&]+)/)){a.width=425;a.height=350;a.params.frameborder="0";a.type="iframe";d="http://www.youtube.com/embed/"+d.match(/v=([^&]+)/)[1];f("src",d)}if(d.match(/video.google.com(.+)docid=([^&]+)/)){a.width=425;a.height=326;a.type="flash";d="http://video.google.com/googleplayer.swf?docId="+d.match(/docid=([^&]+)/)[1]+"&hl=en";
f("src",d)}if(a.type=="video"){if(!a.video.sources)a.video.sources=[];a.video.sources[0]={src:d};if(d=h("video_altsource1"))a.video.sources[1]={src:d};if(d=h("video_altsource2"))a.video.sources[2]={src:d}}else a.params.src=d;f("width",a.width||320);f("height",a.height||240)}},dataToForm:function(){this.moveStates(true)},formToData:function(b){if(b=="source"){this.moveStates(false,b);f("source",this.editor.plugins.media.dataToHtml(this.data));this.panel="source"}else{if(this.panel=="source"){this.data=
this.editor.plugins.media.htmlToData(h("source"));this.dataToForm();this.panel=""}this.moveStates(false,b);this.preview()}},changeSize:function(b){var e,j;if(c("constrain").checked){e=parseInt(h("width")||"320",10);j=parseInt(h("height")||"240",10);b=="width"?f("height",Math.round(e/this.data.width*e)):f("width",Math.round(j/this.data.height*j))}this.formToData()},getMediaListHTML:function(){if(typeof tinyMCEMediaList!="undefined"&&tinyMCEMediaList.length>0){var b="";b+='<select id="linklist" name="linklist" style="width: 250px" onchange="this.form.src.value=this.options[this.selectedIndex].value;Media.formToData(\'src\');">';
b+='<option value="">---</option>';for(var e=0;e<tinyMCEMediaList.length;e++)b+='<option value="'+tinyMCEMediaList[e][1]+'">'+tinyMCEMediaList[e][0]+"</option>";b+="</select>";return b}return""}};tinyMCEPopup.requireLangPack();tinyMCEPopup.onInit.add(function(){Media.init()})})();
