var tinymce=null,tinyMCEPopup,tinyMCE;
tinyMCEPopup={init:function(){var a=this,b;b=a.getWin();tinymce=b.tinymce;tinyMCE=b.tinyMCE;a.editor=tinymce.EditorManager.activeEditor;a.params=a.editor.windowManager.params;a.features=a.editor.windowManager.features;a.dom=a.editor.windowManager.createInstance("tinymce.dom.DOMUtils",document);if(a.features.popup_css!==false)a.dom.loadCSS(a.features.popup_css||a.editor.settings.popup_css);a.listeners=[];a.onInit={add:function(c,d){a.listeners.push({func:c,scope:d})}};a.isWindow=!a.getWindowArg("mce_inline");
a.id=a.getWindowArg("mce_window_id");a.editor.windowManager.onOpen.dispatch(a.editor.windowManager,window)},getWin:function(){return!window.frameElement&&window.dialogArguments||opener||parent||top},getWindowArg:function(a,b){var c=this.params[a];return tinymce.is(c)?c:b},getParam:function(a,b){return this.editor.getParam(a,b)},getLang:function(a,b){return this.editor.getLang(a,b)},execCommand:function(a,b,c,d){d=d||{};d.skip_focus=1;this.restoreSelection();return this.editor.execCommand(a,b,c,d)},
resizeToInnerSize:function(){var a=this;setTimeout(function(){var b=a.dom.getViewPort(window);a.editor.windowManager.resizeBy(a.getWindowArg("mce_width")-b.w,a.getWindowArg("mce_height")-b.h,a.id||window)},10)},executeOnLoad:function(a){this.onInit.add(function(){eval(a)})},storeSelection:function(){this.editor.windowManager.bookmark=tinyMCEPopup.editor.selection.getBookmark(1)},restoreSelection:function(){var a=tinyMCEPopup;!a.isWindow&&tinymce.isIE&&a.editor.selection.moveToBookmark(a.editor.windowManager.bookmark)},
requireLangPack:function(){var a=this.getWindowArg("plugin_url")||this.getWindowArg("theme_url");if(a&&this.editor.settings.language&&this.features.translate_i18n!==false&&this.editor.settings.language_load!==false){a+="/langs/"+this.editor.settings.language+"_dlg.js";if(!tinymce.ScriptLoader.isDone(a)){document.write('<script type="text/javascript" src="'+tinymce._addVer(a)+'"><\/script>');tinymce.ScriptLoader.markDone(a)}}},pickColor:function(a,b){this.execCommand("mceColorPicker",true,{color:document.getElementById(b).value,
func:function(c){document.getElementById(b).value=c;try{document.getElementById(b).onchange()}catch(d){}}})},openBrowser:function(a,b){tinyMCEPopup.restoreSelection();this.editor.execCallback("file_browser_callback",a,document.getElementById(a).value,b,window)},confirm:function(a,b,c){this.editor.windowManager.confirm(a,b,c,window)},alert:function(a,b,c){this.editor.windowManager.alert(a,b,c,window)},close:function(){function a(){b.editor.windowManager.close(window);tinymce=tinyMCE=b.editor=b.params=
b.dom=b.dom.doc=null}var b=this;tinymce.isOpera?b.getWin().setTimeout(a,0):a()},_restoreSelection:function(){var a=window.event.srcElement;if(a.nodeName=="INPUT"&&(a.type=="submit"||a.type=="button"))tinyMCEPopup.restoreSelection()},_onDOMLoaded:function(){var a=tinyMCEPopup,b=document.title,c,d;if(!a.domLoaded){a.domLoaded=1;if(a.features.translate_i18n!==false){c=document.body.innerHTML;if(tinymce.isIE)c=c.replace(/ (value|title|alt)=([^"][^\s>]+)/gi,' $1="$2"');document.dir=a.editor.getParam("directionality",
"");if((d=a.editor.translate(c))&&d!=c)document.body.innerHTML=d;if((d=a.editor.translate(b))&&d!=b)document.title=b=d}if(!a.editor.getParam("browser_preferred_colors",false)||!a.isWindow)a.dom.addClass(document.body,"forceColors");document.body.style.display="";if(tinymce.isIE){document.attachEvent("onmouseup",tinyMCEPopup._restoreSelection);a.dom.add(a.dom.select("head")[0],"base",{target:"_self"})}a.restoreSelection();a.resizeToInnerSize();a.isWindow?window.focus():a.editor.windowManager.setTitle(window,
b);!tinymce.isIE&&!a.isWindow&&tinymce.dom.Event._add(document,"focus",function(){a.editor.windowManager.focus(a.id)});tinymce.each(a.dom.select("select"),function(e){e.onkeydown=tinyMCEPopup._accessHandler});tinymce.each(a.listeners,function(e){e.func.call(e.scope,a.editor)});if(a.getWindowArg("mce_auto_focus",true)){window.focus();tinymce.each(document.forms,function(e){tinymce.each(e.elements,function(f){if(a.dom.hasClass(f,"mceFocus")&&!f.disabled){f.focus();return false}})})}document.onkeyup=
tinyMCEPopup._closeWinKeyHandler}},_accessHandler:function(a){a=a||window.event;if(a.keyCode==13||a.keyCode==32){a=a.target||a.srcElement;a.onchange&&a.onchange();return tinymce.dom.Event.cancel(a)}},_closeWinKeyHandler:function(a){a=a||window.event;a.keyCode==27&&tinyMCEPopup.close()},_wait:function(){if(document.attachEvent){document.attachEvent("onreadystatechange",function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",arguments.callee);tinyMCEPopup._onDOMLoaded()}});
document.documentElement.doScroll&&window==window.top&&function(){if(!tinyMCEPopup.domLoaded){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}tinyMCEPopup._onDOMLoaded()}}();document.attachEvent("onload",tinyMCEPopup._onDOMLoaded)}else if(document.addEventListener){window.addEventListener("DOMContentLoaded",tinyMCEPopup._onDOMLoaded,false);window.addEventListener("load",tinyMCEPopup._onDOMLoaded,false)}}};tinyMCEPopup.init();tinyMCEPopup._wait();
