# Generated by compass-jquery-plugin/gem-tasks/jqtouch.rake
# Install with: compass -f jquery -p jqtouch

file 'config/initializers/jqtouch.rb'
javascript 'jquery.jqtouch.js'
javascript 'jquery.jqtouch.min.js'
stylesheet 'jqtouch/iphone-emulator.sass'
stylesheet 'jqtouch/jqtouch.sass'
