tinyMCEPopup.requireLangPack();
function init(){tinyMCEPopup.resizeToInnerSize();document.getElementById("backgroundimagebrowsercontainer").innerHTML=getBrowserHTML("backgroundimagebrowser","backgroundimage","image","table");document.getElementById("bgcolor_pickcontainer").innerHTML=getColorPickerHTML("bgcolor_pick","bgcolor");var a=tinyMCEPopup.editor,c=a.dom;a=c.getParent(a.selection.getStart(),"tr");var b=document.forms[0],e=c.parseStyle(c.getAttrib(a,"style")),d=a.parentNode.nodeName.toLowerCase(),f=c.getAttrib(a,"align"),g=
c.getAttrib(a,"valign"),h=trimSize(getStyle(a,"height","height")),i=c.getAttrib(a,"class"),j=convertRGBToHex(getStyle(a,"bgcolor","backgroundColor")),k=getStyle(a,"background","backgroundImage").replace(RegExp("url\\(['\"]?([^'\"]*)['\"]?\\)","gi"),"$1"),l=c.getAttrib(a,"id"),m=c.getAttrib(a,"lang"),n=c.getAttrib(a,"dir");selectByValue(b,"rowtype",d);if(c.select("td.mceSelected,th.mceSelected",a).length==0){addClassesToList("class","table_row_styles");TinyMCE_EditableSelects.init();b.bgcolor.value=
j;b.backgroundimage.value=k;b.height.value=h;b.id.value=l;b.lang.value=m;b.style.value=c.serializeStyle(e);selectByValue(b,"align",f);selectByValue(b,"valign",g);selectByValue(b,"class",i,true,true);selectByValue(b,"dir",n);if(isVisible("backgroundimagebrowser"))document.getElementById("backgroundimage").style.width="180px";updateColor("bgcolor_pick","bgcolor")}else tinyMCEPopup.dom.hide("action")}
function updateAction(){var a=tinyMCEPopup.editor,c=a.dom,b,e,d=getSelectValue(document.forms[0],"action");tinyMCEPopup.restoreSelection();b=c.getParent(a.selection.getStart(),"tr");e=c.getParent(a.selection.getStart(),"table");if(c.select("td.mceSelected,th.mceSelected",b).length>0)tinymce.each(e.rows,function(f){var g;for(g=0;g<f.cells.length;g++)if(c.hasClass(f.cells[g],"mceSelected")){updateRow(f,true);break}});else switch(d){case "row":updateRow(b);break;case "all":b=e.getElementsByTagName("tr");
for(e=0;e<b.length;e++)updateRow(b[e],true);break;case "odd":case "even":b=e.getElementsByTagName("tr");for(e=0;e<b.length;e++)if(e%2==0&&d=="odd"||e%2!=0&&d=="even")updateRow(b[e],true,true)}a.addVisual();a.nodeChanged();a.execCommand("mceEndUndoLevel");tinyMCEPopup.close()}
function updateRow(a,c,b){var e=tinyMCEPopup.editor,d=document.forms[0],f=e.dom,g=a.parentNode.nodeName.toLowerCase(),h=getSelectValue(d,"rowtype"),i=e.getDoc();c||f.setAttrib(a,"id",d.id.value);f.setAttrib(a,"align",getSelectValue(d,"align"));f.setAttrib(a,"vAlign",getSelectValue(d,"valign"));f.setAttrib(a,"lang",d.lang.value);f.setAttrib(a,"dir",getSelectValue(d,"dir"));f.setAttrib(a,"style",f.serializeStyle(f.parseStyle(d.style.value)));f.setAttrib(a,"class",getSelectValue(d,"class"));f.setAttrib(a,
"background","");f.setAttrib(a,"bgColor","");f.setAttrib(a,"height","");a.style.height=getCSSSize(d.height.value);a.style.backgroundColor=d.bgcolor.value;a.style.backgroundImage=d.backgroundimage.value!=""?"url('"+d.backgroundimage.value+"')":"";if(g!=h&&!b){c=a.cloneNode(1);b=f.getParent(a,"table");d=null;for(g=0;g<b.childNodes.length;g++)if(b.childNodes[g].nodeName.toLowerCase()==h)d=b.childNodes[g];if(d==null){d=i.createElement(h);b.firstChild.nodeName=="CAPTION"?e.dom.insertAfter(d,b.firstChild):
b.insertBefore(d,b.firstChild)}d.appendChild(c);a.parentNode.removeChild(a);a=c}f.setAttrib(a,"style",f.serializeStyle(f.parseStyle(a.style.cssText)))}function changedBackgroundImage(){var a=document.forms[0],c=tinyMCEPopup.editor.dom,b=c.parseStyle(a.style.value);b["background-image"]="url('"+a.backgroundimage.value+"')";a.style.value=c.serializeStyle(b)}
function changedStyle(){var a=document.forms[0],c=tinyMCEPopup.editor.dom.parseStyle(a.style.value);a.backgroundimage.value=c["background-image"]?c["background-image"].replace(RegExp("url\\('?([^']*)'?\\)","gi"),"$1"):"";if(c.height)a.height.value=trimSize(c.height);if(c["background-color"]){a.bgcolor.value=c["background-color"];updateColor("bgcolor_pick","bgcolor")}}
function changedSize(){var a=document.forms[0],c=tinyMCEPopup.editor.dom,b=c.parseStyle(a.style.value),e=a.height.value;b.height=e!=""?getCSSSize(e):"";a.style.value=c.serializeStyle(b)}function changedColor(){var a=document.forms[0],c=tinyMCEPopup.editor.dom,b=c.parseStyle(a.style.value);b["background-color"]=a.bgcolor.value;a.style.value=c.serializeStyle(b)}tinyMCEPopup.onInit.add(init);
