tinyMCEPopup.requireLangPack();var action,orgTableWidth,orgTableHeight,dom=tinyMCEPopup.editor.dom;
function insertTable(){var b=document.forms[0],a=tinyMCEPopup.editor,c=a.dom,i=2,m=2,k=0,n=-1,o=-1,p,j,l,u,q,v,w,f="",d,r,s,t;tinyMCEPopup.restoreSelection();if(!AutoValidator.validate(b)){tinyMCEPopup.alert(AutoValidator.getErrorMessages(b).join(". ")+".");return false}d=c.getParent(a.selection.getNode(),"table");i=b.elements.cols.value;m=b.elements.rows.value;k=b.elements.border.value!=""?b.elements.border.value:0;n=b.elements.cellpadding.value!=""?b.elements.cellpadding.value:"";o=b.elements.cellspacing.value!=
""?b.elements.cellspacing.value:"";p=getSelectValue(b,"align");v=getSelectValue(b,"tframe");w=getSelectValue(b,"rules");j=b.elements.width.value;l=b.elements.height.value;bordercolor=b.elements.bordercolor.value;bgcolor=b.elements.bgcolor.value;u=getSelectValue(b,"class");id=b.elements.id.value;summary=b.elements.summary.value;style=b.elements.style.value;dir=b.elements.dir.value;lang=b.elements.lang.value;background=b.elements.backgroundimage.value;q=b.elements.caption.checked;r=tinyMCEPopup.getParam("table_cell_limit",
false);s=tinyMCEPopup.getParam("table_row_limit",false);if((t=tinyMCEPopup.getParam("table_col_limit",false))&&i>t){tinyMCEPopup.alert(a.getLang("table_dlg.col_limit").replace(/\{\$cols\}/g,t));return false}else if(s&&m>s){tinyMCEPopup.alert(a.getLang("table_dlg.row_limit").replace(/\{\$rows\}/g,s));return false}else if(r&&i*m>r){tinyMCEPopup.alert(a.getLang("table_dlg.cell_limit").replace(/\{\$cells\}/g,r));return false}if(action=="update"){c.setAttrib(d,"cellPadding",n,true);c.setAttrib(d,"cellSpacing",
o,true);c.setAttrib(d,"border",k);c.setAttrib(d,"align",p);c.setAttrib(d,"frame",v);c.setAttrib(d,"rules",w);c.setAttrib(d,"class",u);c.setAttrib(d,"style",style);c.setAttrib(d,"id",id);c.setAttrib(d,"summary",summary);c.setAttrib(d,"dir",dir);c.setAttrib(d,"lang",lang);(i=a.dom.select("caption",d)[0])&&!q&&i.parentNode.removeChild(i);if(!i&&q){i=d.ownerDocument.createElement("caption");if(!tinymce.isIE)i.innerHTML='<br data-mce-bogus="1"/>';d.insertBefore(i,d.firstChild)}if(j&&a.settings.inline_styles){c.setStyle(d,
"width",j);c.setAttrib(d,"width","")}else{c.setAttrib(d,"width",j,true);c.setStyle(d,"width","")}c.setAttrib(d,"borderColor","");c.setAttrib(d,"bgColor","");c.setAttrib(d,"background","");if(l&&a.settings.inline_styles){c.setStyle(d,"height",l);c.setAttrib(d,"height","")}else{c.setAttrib(d,"height",l,true);c.setStyle(d,"height","")}d.style.backgroundImage=background!=""?"url('"+background+"')":"";if(bordercolor!=""){d.style.borderColor=bordercolor;d.style.borderStyle=d.style.borderStyle==""?"solid":
d.style.borderStyle;d.style.borderWidth=k==""?"1px":k}else d.style.borderColor="";d.style.backgroundColor=bgcolor;d.style.height=getCSSSize(l);a.addVisual();a.nodeChanged();a.execCommand("mceEndUndoLevel");if(b.width.value!=orgTableWidth||b.height.value!=orgTableHeight)a.execCommand("mceRepaint");tinyMCEPopup.close();return true}f+="<table";f+=makeAttrib("id",id);f+=makeAttrib("border",k);f+=makeAttrib("cellpadding",n);f+=makeAttrib("cellspacing",o);f+=makeAttrib("data-mce-new","1");if(j&&a.settings.inline_styles){if(style)style+=
"; ";if(/^[0-9\.]+$/.test(j))j+="px";style+="width: "+j}else f+=makeAttrib("width",j);f+=makeAttrib("align",p);f+=makeAttrib("frame",v);f+=makeAttrib("rules",w);f+=makeAttrib("class",u);f+=makeAttrib("style",style);f+=makeAttrib("summary",summary);f+=makeAttrib("dir",dir);f+=makeAttrib("lang",lang);f+=">";if(q)f+=tinymce.isIE?"<caption></caption>":'<caption><br data-mce-bogus="1"/></caption>';for(b=0;b<m;b++){f+="<tr>";for(k=0;k<i;k++)f+=tinymce.isIE?"<td></td>":'<td><br data-mce-bogus="1"/></td>';
f+="</tr>"}f+="</table>";if(a.settings.fix_table_elements){var h="";a.focus();a.selection.setContent('<br class="_mce_marker" />');tinymce.each("h1,h2,h3,h4,h5,h6,p".split(","),function(e){if(h)h+=",";h+=e+" ._mce_marker"});tinymce.each(a.dom.select(h),function(e){a.dom.split(a.dom.getParent(e,"h1,h2,h3,h4,h5,h6,p"),e)});c.setOuterHTML(c.select("br._mce_marker")[0],f)}else a.execCommand("mceInsertContent",false,f);tinymce.each(c.select("table[data-mce-new]"),function(e){var g=c.select("td",e);try{a.selection.select(g[0],
true);a.selection.collapse()}catch(x){}c.setAttrib(e,"data-mce-new","")});a.addVisual();a.execCommand("mceEndUndoLevel");tinyMCEPopup.close()}function makeAttrib(b,a){var c=document.forms[0].elements[b];if(typeof a=="undefined"||a==null){a="";if(c)a=c.value}if(a=="")return"";a=a.replace(/&/g,"&amp;");a=a.replace(/\"/g,"&quot;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");return" "+b+'="'+a+'"'}
function init(){tinyMCEPopup.resizeToInnerSize();document.getElementById("backgroundimagebrowsercontainer").innerHTML=getBrowserHTML("backgroundimagebrowser","backgroundimage","image","table");document.getElementById("backgroundimagebrowsercontainer").innerHTML=getBrowserHTML("backgroundimagebrowser","backgroundimage","image","table");document.getElementById("bordercolor_pickcontainer").innerHTML=getColorPickerHTML("bordercolor_pick","bordercolor");document.getElementById("bgcolor_pickcontainer").innerHTML=
getColorPickerHTML("bgcolor_pick","bgcolor");var b=2,a=2,c=tinyMCEPopup.getParam("table_default_border","0"),i=tinyMCEPopup.getParam("table_default_cellpadding",""),m=tinyMCEPopup.getParam("table_default_cellspacing",""),k="",n="",o="",p="",j="",l="",u="",q="",v="",w="",f="",d="",r=p=j="",s="",t=tinyMCEPopup.editor,h=t.dom,e=document.forms[0],g=h.getParent(t.selection.getNode(),"table");(action=tinyMCEPopup.getWindowArg("action"))||(action=g?"update":"insert");if(g&&action!="insert"){a=g.rows;for(c=
b=0;c<a.length;c++)if(a[c].cells.length>b)b=a[c].cells.length;a=a.length;st=h.parseStyle(h.getAttrib(g,"style"));c=trimSize(getStyle(g,"border","borderWidth"));i=h.getAttrib(g,"cellpadding","");m=h.getAttrib(g,"cellspacing","");n=trimSize(getStyle(g,"width","width"));o=trimSize(getStyle(g,"height","height"));p=convertRGBToHex(getStyle(g,"bordercolor","borderLeftColor"));j=convertRGBToHex(getStyle(g,"bgcolor","backgroundColor"));k=h.getAttrib(g,"align",k);s=h.getAttrib(g,"frame");r=h.getAttrib(g,"rules");
l=tinymce.trim(h.getAttrib(g,"class").replace(/mceItem.+/g,""));u=h.getAttrib(g,"id");q=h.getAttrib(g,"summary");v=h.serializeStyle(st);w=h.getAttrib(g,"dir");f=h.getAttrib(g,"lang");d=getStyle(g,"background","backgroundImage").replace(RegExp("url\\(['\"]?([^'\"]*)['\"]?\\)","gi"),"$1");e.caption.checked=g.getElementsByTagName("caption").length>0;orgTableWidth=n;orgTableHeight=o;action="update";e.insert.value=t.getLang("update")}addClassesToList("class","table_styles");TinyMCE_EditableSelects.init();
selectByValue(e,"align",k);selectByValue(e,"tframe",s);selectByValue(e,"rules",r);selectByValue(e,"class",l,true,true);e.cols.value=b;e.rows.value=a;e.border.value=c;e.cellpadding.value=i;e.cellspacing.value=m;e.width.value=n;e.height.value=o;e.bordercolor.value=p;e.bgcolor.value=j;e.id.value=u;e.summary.value=q;e.style.value=v;e.dir.value=w;e.lang.value=f;e.backgroundimage.value=d;updateColor("bordercolor_pick","bordercolor");updateColor("bgcolor_pick","bgcolor");if(isVisible("backgroundimagebrowser"))document.getElementById("backgroundimage").style.width=
"180px";if(action=="update"){e.cols.disabled=true;e.rows.disabled=true}}function changedSize(){var b=document.forms[0],a=dom.parseStyle(b.style.value),c=b.height.value;a.height=c!=""?getCSSSize(c):"";b.style.value=dom.serializeStyle(a)}function changedBackgroundImage(){var b=document.forms[0],a=dom.parseStyle(b.style.value);a["background-image"]="url('"+b.backgroundimage.value+"')";b.style.value=dom.serializeStyle(a)}
function changedBorder(){var b=document.forms[0],a=dom.parseStyle(b.style.value);if(b.border.value!=""&&b.bordercolor.value!="")a["border-width"]=b.border.value+"px";b.style.value=dom.serializeStyle(a)}
function changedColor(){var b=document.forms[0],a=dom.parseStyle(b.style.value);a["background-color"]=b.bgcolor.value;if(b.bordercolor.value!=""){a["border-color"]=b.bordercolor.value;a["border-width"]||(a["border-width"]=b.border.value==""?"1px":b.border.value+"px")}b.style.value=dom.serializeStyle(a)}
function changedStyle(){var b=document.forms[0],a=dom.parseStyle(b.style.value);b.backgroundimage.value=a["background-image"]?a["background-image"].replace(RegExp("url\\(['\"]?([^'\"]*)['\"]?\\)","gi"),"$1"):"";if(a.width)b.width.value=trimSize(a.width);if(a.height)b.height.value=trimSize(a.height);if(a["background-color"]){b.bgcolor.value=a["background-color"];updateColor("bgcolor_pick","bgcolor")}if(a["border-color"]){b.bordercolor.value=a["border-color"];updateColor("bordercolor_pick","bordercolor")}}
tinyMCEPopup.onInit.add(init);
