# Generated by compass-jquery-plugin/gem-tasks/ical.rake
# Install with: compass install jquery/ical

file 'app/views/shared/_ui_event_for.js.haml'
file 'config/initializers/ical.rb'
javascript 'jquery.ical.js'
javascript 'jquery.ical.min.js'
stylesheet 'jquery/ical.scss'
image 'jquery/ical/calendar.png'
image 'jquery/ical/clock.png'
