# Generated by compass-jquery-plugin/gem-tasks/emulators.rake
# Install with: compass install jquery/emulators

file 'config/initializers/emulators.rb'
stylesheet 'ipad.landscape.scss'
stylesheet 'iphone.portrait.scss'
image 'emulators/ipad_landscape.png'
image 'emulators/iphone_portrait.png'
