# Generated by compass-jquery-plugin/gem-tasks/jquery.rake
# Install with: compass install jquery/jquery . --force

file 'config/initializers/jquery.rb'
file 'lib/tasks/haml.rake'
file 'lib/tasks/haml.rake'
javascript 'jquery.js'
javascript 'jquery.min.js'
