tinyMCEPopup.requireLangPack();
var defaultFonts="Arial, Helvetica, sans-serif=Arial, Helvetica, sans-serif;Times New Roman, Times, serif=Times New Roman, Times, serif;Courier New, Courier, mono=Courier New, Courier, mono;Times New Roman, Times, serif=Times New Roman, Times, serif;Georgia, Times New Roman, Times, serif=Georgia, Times New Roman, Times, serif;Verdana, Arial, Helvetica, sans-serif=Verdana, Arial, Helvetica, sans-serif;Geneva, Arial, Helvetica, sans-serif=Geneva, Arial, Helvetica, sans-serif",defaultSizes="9;10;12;14;16;18;24;xx-small;x-small;small;medium;large;x-large;xx-large;smaller;larger",
defaultMeasurement="+pixels=px;points=pt;inches=in;centimetres=cm;millimetres=mm;picas=pc;ems=em;exs=ex;%",defaultSpacingMeasurement="pixels=px;points=pt;inches=in;centimetres=cm;millimetres=mm;picas=pc;+ems=em;exs=ex;%",defaultIndentMeasurement="pixels=px;+points=pt;inches=in;centimetres=cm;millimetres=mm;picas=pc;ems=em;exs=ex;%",defaultWeight="normal;bold;bolder;lighter;100;200;300;400;500;600;700;800;900",defaultTextStyle="normal;italic;oblique",defaultVariant="normal;small-caps",defaultLineHeight=
"normal",defaultAttachment="fixed;scroll",defaultRepeat="no-repeat;repeat;repeat-x;repeat-y",defaultPosH="left;center;right",defaultPosV="top;center;bottom",defaultVAlign="baseline;sub;super;top;text-top;middle;bottom;text-bottom",defaultDisplay="inline;block;list-item;run-in;compact;marker;table;inline-table;table-row-group;table-header-group;table-footer-group;table-row;table-column-group;table-column;table-cell;table-caption;none",defaultBorderStyle="none;solid;dashed;dotted;double;groove;ridge;inset;outset",
defaultBorderWidth="thin;medium;thick",defaultListType="disc;circle;square;decimal;lower-roman;upper-roman;lower-alpha;upper-alpha;none";
function init(){var b;document.getElementById("container").style.cssText=tinyMCEPopup.getWindowArg("style_text");b=getBrowserHTML("background_image_browser","background_image","image","advimage");document.getElementById("background_image_browser").innerHTML=b;document.getElementById("text_color_pickcontainer").innerHTML=getColorPickerHTML("text_color_pick","text_color");document.getElementById("background_color_pickcontainer").innerHTML=getColorPickerHTML("background_color_pick","background_color");
document.getElementById("border_color_top_pickcontainer").innerHTML=getColorPickerHTML("border_color_top_pick","border_color_top");document.getElementById("border_color_right_pickcontainer").innerHTML=getColorPickerHTML("border_color_right_pick","border_color_right");document.getElementById("border_color_bottom_pickcontainer").innerHTML=getColorPickerHTML("border_color_bottom_pick","border_color_bottom");document.getElementById("border_color_left_pickcontainer").innerHTML=getColorPickerHTML("border_color_left_pick",
"border_color_left");fillSelect(0,"text_font","style_font",defaultFonts,";",true);fillSelect(0,"text_size","style_font_size",defaultSizes,";",true);fillSelect(0,"text_size_measurement","style_font_size_measurement",defaultMeasurement,";",true);fillSelect(0,"text_case","style_text_case","capitalize;uppercase;lowercase",";",true);fillSelect(0,"text_weight","style_font_weight",defaultWeight,";",true);fillSelect(0,"text_style","style_font_style",defaultTextStyle,";",true);fillSelect(0,"text_variant",
"style_font_variant",defaultVariant,";",true);fillSelect(0,"text_lineheight","style_font_line_height",defaultLineHeight,";",true);fillSelect(0,"text_lineheight_measurement","style_font_line_height_measurement",defaultMeasurement,";",true);fillSelect(0,"background_attachment","style_background_attachment",defaultAttachment,";",true);fillSelect(0,"background_repeat","style_background_repeat",defaultRepeat,";",true);fillSelect(0,"background_hpos_measurement","style_background_hpos_measurement",defaultMeasurement,
";",true);fillSelect(0,"background_vpos_measurement","style_background_vpos_measurement",defaultMeasurement,";",true);fillSelect(0,"background_hpos","style_background_hpos",defaultPosH,";",true);fillSelect(0,"background_vpos","style_background_vpos",defaultPosV,";",true);fillSelect(0,"block_wordspacing","style_wordspacing","normal",";",true);fillSelect(0,"block_wordspacing_measurement","style_wordspacing_measurement",defaultSpacingMeasurement,";",true);fillSelect(0,"block_letterspacing","style_letterspacing",
"normal",";",true);fillSelect(0,"block_letterspacing_measurement","style_letterspacing_measurement",defaultSpacingMeasurement,";",true);fillSelect(0,"block_vertical_alignment","style_vertical_alignment",defaultVAlign,";",true);fillSelect(0,"block_text_align","style_text_align","left;right;center;justify",";",true);fillSelect(0,"block_whitespace","style_whitespace","normal;pre;nowrap",";",true);fillSelect(0,"block_display","style_display",defaultDisplay,";",true);fillSelect(0,"block_text_indent_measurement",
"style_text_indent_measurement",defaultIndentMeasurement,";",true);fillSelect(0,"box_width_measurement","style_box_width_measurement",defaultMeasurement,";",true);fillSelect(0,"box_height_measurement","style_box_height_measurement",defaultMeasurement,";",true);fillSelect(0,"box_float","style_float","left;right;none",";",true);fillSelect(0,"box_clear","style_clear","left;right;both;none",";",true);fillSelect(0,"box_padding_left_measurement","style_padding_left_measurement",defaultMeasurement,";",true);
fillSelect(0,"box_padding_top_measurement","style_padding_top_measurement",defaultMeasurement,";",true);fillSelect(0,"box_padding_bottom_measurement","style_padding_bottom_measurement",defaultMeasurement,";",true);fillSelect(0,"box_padding_right_measurement","style_padding_right_measurement",defaultMeasurement,";",true);fillSelect(0,"box_margin_left_measurement","style_margin_left_measurement",defaultMeasurement,";",true);fillSelect(0,"box_margin_top_measurement","style_margin_top_measurement",defaultMeasurement,
";",true);fillSelect(0,"box_margin_bottom_measurement","style_margin_bottom_measurement",defaultMeasurement,";",true);fillSelect(0,"box_margin_right_measurement","style_margin_right_measurement",defaultMeasurement,";",true);fillSelect(0,"border_style_top","style_border_style_top",defaultBorderStyle,";",true);fillSelect(0,"border_style_right","style_border_style_right",defaultBorderStyle,";",true);fillSelect(0,"border_style_bottom","style_border_style_bottom",defaultBorderStyle,";",true);fillSelect(0,
"border_style_left","style_border_style_left",defaultBorderStyle,";",true);fillSelect(0,"border_width_top","style_border_width_top",defaultBorderWidth,";",true);fillSelect(0,"border_width_right","style_border_width_right",defaultBorderWidth,";",true);fillSelect(0,"border_width_bottom","style_border_width_bottom",defaultBorderWidth,";",true);fillSelect(0,"border_width_left","style_border_width_left",defaultBorderWidth,";",true);fillSelect(0,"border_width_top_measurement","style_border_width_top_measurement",
defaultMeasurement,";",true);fillSelect(0,"border_width_right_measurement","style_border_width_right_measurement",defaultMeasurement,";",true);fillSelect(0,"border_width_bottom_measurement","style_border_width_bottom_measurement",defaultMeasurement,";",true);fillSelect(0,"border_width_left_measurement","style_border_width_left_measurement",defaultMeasurement,";",true);fillSelect(0,"list_type","style_list_type",defaultListType,";",true);fillSelect(0,"list_position","style_list_position","inside;outside",
";",true);fillSelect(0,"positioning_type","style_positioning_type","absolute;relative;static",";",true);fillSelect(0,"positioning_visibility","style_positioning_visibility","inherit;visible;hidden",";",true);fillSelect(0,"positioning_width_measurement","style_positioning_width_measurement",defaultMeasurement,";",true);fillSelect(0,"positioning_height_measurement","style_positioning_height_measurement",defaultMeasurement,";",true);fillSelect(0,"positioning_overflow","style_positioning_overflow","visible;hidden;scroll;auto",
";",true);fillSelect(0,"positioning_placement_top_measurement","style_positioning_placement_top_measurement",defaultMeasurement,";",true);fillSelect(0,"positioning_placement_right_measurement","style_positioning_placement_right_measurement",defaultMeasurement,";",true);fillSelect(0,"positioning_placement_bottom_measurement","style_positioning_placement_bottom_measurement",defaultMeasurement,";",true);fillSelect(0,"positioning_placement_left_measurement","style_positioning_placement_left_measurement",
defaultMeasurement,";",true);fillSelect(0,"positioning_clip_top_measurement","style_positioning_clip_top_measurement",defaultMeasurement,";",true);fillSelect(0,"positioning_clip_right_measurement","style_positioning_clip_right_measurement",defaultMeasurement,";",true);fillSelect(0,"positioning_clip_bottom_measurement","style_positioning_clip_bottom_measurement",defaultMeasurement,";",true);fillSelect(0,"positioning_clip_left_measurement","style_positioning_clip_left_measurement",defaultMeasurement,
";",true);TinyMCE_EditableSelects.init();setupFormData();showDisabledControls()}
function setupFormData(){var b=document.getElementById("container"),a=document.forms[0];selectByValue(a,"text_font",b.style.fontFamily,true,true);selectByValue(a,"text_size",getNum(b.style.fontSize),true,true);selectByValue(a,"text_size_measurement",getMeasurement(b.style.fontSize));selectByValue(a,"text_weight",b.style.fontWeight,true,true);selectByValue(a,"text_style",b.style.fontStyle,true,true);selectByValue(a,"text_lineheight",getNum(b.style.lineHeight),true,true);selectByValue(a,"text_lineheight_measurement",
getMeasurement(b.style.lineHeight));selectByValue(a,"text_case",b.style.textTransform,true,true);selectByValue(a,"text_variant",b.style.fontVariant,true,true);a.text_color.value=tinyMCEPopup.editor.dom.toHex(b.style.color);updateColor("text_color_pick","text_color");a.text_underline.checked=inStr(b.style.textDecoration,"underline");a.text_overline.checked=inStr(b.style.textDecoration,"overline");a.text_linethrough.checked=inStr(b.style.textDecoration,"line-through");a.text_blink.checked=inStr(b.style.textDecoration,
"blink");a.background_color.value=tinyMCEPopup.editor.dom.toHex(b.style.backgroundColor);updateColor("background_color_pick","background_color");a.background_image.value=b.style.backgroundImage.replace(RegExp("url\\('?([^']*)'?\\)","gi"),"$1");selectByValue(a,"background_repeat",b.style.backgroundRepeat,true,true);selectByValue(a,"background_attachment",b.style.backgroundAttachment,true,true);selectByValue(a,"background_hpos",getNum(getVal(b.style.backgroundPosition,0)),true,true);selectByValue(a,
"background_hpos_measurement",getMeasurement(getVal(b.style.backgroundPosition,0)));selectByValue(a,"background_vpos",getNum(getVal(b.style.backgroundPosition,1)),true,true);selectByValue(a,"background_vpos_measurement",getMeasurement(getVal(b.style.backgroundPosition,1)));selectByValue(a,"block_wordspacing",getNum(b.style.wordSpacing),true,true);selectByValue(a,"block_wordspacing_measurement",getMeasurement(b.style.wordSpacing));selectByValue(a,"block_letterspacing",getNum(b.style.letterSpacing),
true,true);selectByValue(a,"block_letterspacing_measurement",getMeasurement(b.style.letterSpacing));selectByValue(a,"block_vertical_alignment",b.style.verticalAlign,true,true);selectByValue(a,"block_text_align",b.style.textAlign,true,true);a.block_text_indent.value=getNum(b.style.textIndent);selectByValue(a,"block_text_indent_measurement",getMeasurement(b.style.textIndent));selectByValue(a,"block_whitespace",b.style.whiteSpace,true,true);selectByValue(a,"block_display",b.style.display,true,true);
a.box_width.value=getNum(b.style.width);selectByValue(a,"box_width_measurement",getMeasurement(b.style.width));a.box_height.value=getNum(b.style.height);selectByValue(a,"box_height_measurement",getMeasurement(b.style.height));selectByValue(a,"box_float",b.style.cssFloat||b.style.styleFloat,true,true);selectByValue(a,"box_clear",b.style.clear,true,true);setupBox(a,b,"box_padding","padding","");setupBox(a,b,"box_margin","margin","");setupBox(a,b,"border_style","border","Style");setupBox(a,b,"border_width",
"border","Width");setupBox(a,b,"border_color","border","Color");updateColor("border_color_top_pick","border_color_top");updateColor("border_color_right_pick","border_color_right");updateColor("border_color_bottom_pick","border_color_bottom");updateColor("border_color_left_pick","border_color_left");a.elements.border_color_top.value=tinyMCEPopup.editor.dom.toHex(a.elements.border_color_top.value);a.elements.border_color_right.value=tinyMCEPopup.editor.dom.toHex(a.elements.border_color_right.value);
a.elements.border_color_bottom.value=tinyMCEPopup.editor.dom.toHex(a.elements.border_color_bottom.value);a.elements.border_color_left.value=tinyMCEPopup.editor.dom.toHex(a.elements.border_color_left.value);selectByValue(a,"list_type",b.style.listStyleType,true,true);selectByValue(a,"list_position",b.style.listStylePosition,true,true);a.list_bullet_image.value=b.style.listStyleImage.replace(RegExp("url\\('?([^']*)'?\\)","gi"),"$1");selectByValue(a,"positioning_type",b.style.position,true,true);selectByValue(a,
"positioning_visibility",b.style.visibility,true,true);selectByValue(a,"positioning_overflow",b.style.overflow,true,true);a.positioning_zindex.value=b.style.zIndex?b.style.zIndex:"";a.positioning_width.value=getNum(b.style.width);selectByValue(a,"positioning_width_measurement",getMeasurement(b.style.width));a.positioning_height.value=getNum(b.style.height);selectByValue(a,"positioning_height_measurement",getMeasurement(b.style.height));setupBox(a,b,"positioning_placement","","",["top","right","bottom",
"left"]);b=b.style.clip.replace(RegExp("rect\\('?([^']*)'?\\)","gi"),"$1");b=b.replace(/,/g," ");if(hasEqualValues([getVal(b,0),getVal(b,1),getVal(b,2),getVal(b,3)])){a.positioning_clip_top.value=getNum(getVal(b,0));selectByValue(a,"positioning_clip_top_measurement",getMeasurement(getVal(b,0)));a.positioning_clip_right.value=a.positioning_clip_bottom.value=a.positioning_clip_left.value}else{a.positioning_clip_top.value=getNum(getVal(b,0));selectByValue(a,"positioning_clip_top_measurement",getMeasurement(getVal(b,
0)));a.positioning_clip_right.value=getNum(getVal(b,1));selectByValue(a,"positioning_clip_right_measurement",getMeasurement(getVal(b,1)));a.positioning_clip_bottom.value=getNum(getVal(b,2));selectByValue(a,"positioning_clip_bottom_measurement",getMeasurement(getVal(b,2)));a.positioning_clip_left.value=getNum(getVal(b,3));selectByValue(a,"positioning_clip_left_measurement",getMeasurement(getVal(b,3)))}}function getMeasurement(b){return b.replace(/^([0-9.]+)(.*)$/,"$2")}
function getNum(b){if(RegExp("^(?:[0-9.]+)(?:[a-z%]+)$","gi").test(b))return b.replace(/[^0-9.]/g,"");return b}function inStr(b,a){return RegExp(a,"gi").test(b)}function getVal(b,a){var c=b.split(" ");if(c.length>1)return c[a];return""}function setValue(b,a,c){if(b.elements[a].type=="text")b.elements[a].value=c;else selectByValue(b,a,c,true,true)}
function setupBox(b,a,c,e,d,f){if(typeof f=="undefined")f=["Top","Right","Bottom","Left"];if(isSame(a,e,d,f)){b.elements[c+"_same"].checked=true;setValue(b,c+"_top",getNum(a.style[e+f[0]+d]));b.elements[c+"_top"].disabled=false;b.elements[c+"_right"].value="";b.elements[c+"_right"].disabled=true;b.elements[c+"_bottom"].value="";b.elements[c+"_bottom"].disabled=true;b.elements[c+"_left"].value="";b.elements[c+"_left"].disabled=true;if(b.elements[c+"_top_measurement"]){selectByValue(b,c+"_top_measurement",
getMeasurement(a.style[e+f[0]+d]));b.elements[c+"_left_measurement"].disabled=true;b.elements[c+"_bottom_measurement"].disabled=true;b.elements[c+"_right_measurement"].disabled=true}}else{b.elements[c+"_same"].checked=false;setValue(b,c+"_top",getNum(a.style[e+f[0]+d]));b.elements[c+"_top"].disabled=false;setValue(b,c+"_right",getNum(a.style[e+f[1]+d]));b.elements[c+"_right"].disabled=false;setValue(b,c+"_bottom",getNum(a.style[e+f[2]+d]));b.elements[c+"_bottom"].disabled=false;setValue(b,c+"_left",
getNum(a.style[e+f[3]+d]));b.elements[c+"_left"].disabled=false;if(b.elements[c+"_top_measurement"]){selectByValue(b,c+"_top_measurement",getMeasurement(a.style[e+f[0]+d]));selectByValue(b,c+"_right_measurement",getMeasurement(a.style[e+f[1]+d]));selectByValue(b,c+"_bottom_measurement",getMeasurement(a.style[e+f[2]+d]));selectByValue(b,c+"_left_measurement",getMeasurement(a.style[e+f[3]+d]));b.elements[c+"_left_measurement"].disabled=false;b.elements[c+"_bottom_measurement"].disabled=false;b.elements[c+
"_right_measurement"].disabled=false}}}function isSame(b,a,c,e){var d=[];if(typeof e=="undefined")e=["Top","Right","Bottom","Left"];if(typeof c=="undefined"||c==null)c="";d[0]=b.style[a+e[0]+c];d[1]=b.style[a+e[1]+c];d[2]=b.style[a+e[2]+c];d[3]=b.style[a+e[3]+c];for(b=0;b<d.length;b++){if(d[b]==null)return false;for(a=0;a<d.length;a++)if(d[a]!=d[b])return false}return true}
function hasEqualValues(b){var a,c;for(a=0;a<b.length;a++){if(b[a]==null)return false;for(c=0;c<b.length;c++)if(b[c]!=b[a])return false}return true}function applyAction(){var b=document.getElementById("container"),a=tinyMCEPopup.editor;generateCSS();tinyMCEPopup.restoreSelection();a.dom.setAttrib(a.selection.getNode(),"style",tinyMCEPopup.editor.dom.serializeStyle(tinyMCEPopup.editor.dom.parseStyle(b.style.cssText)))}function updateAction(){applyAction();tinyMCEPopup.close()}
function generateCSS(){var b=document.getElementById("container"),a=document.forms[0],c;b.style.cssText="";b.style.fontFamily=a.text_font.value;b.style.fontSize=a.text_size.value+(isNum(a.text_size.value)?a.text_size_measurement.value||"px":"");b.style.fontStyle=a.text_style.value;b.style.lineHeight=a.text_lineheight.value+(isNum(a.text_lineheight.value)?a.text_lineheight_measurement.value:"");b.style.textTransform=a.text_case.value;b.style.fontWeight=a.text_weight.value;b.style.fontVariant=a.text_variant.value;
b.style.color=a.text_color.value;c="";c+=a.text_underline.checked?" underline":"";c+=a.text_overline.checked?" overline":"";c+=a.text_linethrough.checked?" line-through":"";c+=a.text_blink.checked?" blink":"";c=c.length>0?c.substring(1):c;if(a.text_none.checked)c="none";b.style.textDecoration=c;b.style.backgroundColor=a.background_color.value;b.style.backgroundImage=a.background_image.value!=""?"url("+a.background_image.value+")":"";b.style.backgroundRepeat=a.background_repeat.value;b.style.backgroundAttachment=
a.background_attachment.value;if(a.background_hpos.value!=""){c="";c+=a.background_hpos.value+(isNum(a.background_hpos.value)?a.background_hpos_measurement.value:"")+" ";c+=a.background_vpos.value+(isNum(a.background_vpos.value)?a.background_vpos_measurement.value:"");b.style.backgroundPosition=c}b.style.wordSpacing=a.block_wordspacing.value+(isNum(a.block_wordspacing.value)?a.block_wordspacing_measurement.value:"");b.style.letterSpacing=a.block_letterspacing.value+(isNum(a.block_letterspacing.value)?
a.block_letterspacing_measurement.value:"");b.style.verticalAlign=a.block_vertical_alignment.value;b.style.textAlign=a.block_text_align.value;b.style.textIndent=a.block_text_indent.value+(isNum(a.block_text_indent.value)?a.block_text_indent_measurement.value:"");b.style.whiteSpace=a.block_whitespace.value;b.style.display=a.block_display.value;b.style.width=a.box_width.value+(isNum(a.box_width.value)?a.box_width_measurement.value:"");b.style.height=a.box_height.value+(isNum(a.box_height.value)?a.box_height_measurement.value:
"");b.style.styleFloat=a.box_float.value;b.style.cssFloat=a.box_float.value;b.style.clear=a.box_clear.value;if(a.box_padding_same.checked)b.style.padding=a.box_padding_top.value+(isNum(a.box_padding_top.value)?a.box_padding_top_measurement.value:"");else{b.style.paddingTop=a.box_padding_top.value+(isNum(a.box_padding_top.value)?a.box_padding_top_measurement.value:"");b.style.paddingRight=a.box_padding_right.value+(isNum(a.box_padding_right.value)?a.box_padding_right_measurement.value:"");b.style.paddingBottom=
a.box_padding_bottom.value+(isNum(a.box_padding_bottom.value)?a.box_padding_bottom_measurement.value:"");b.style.paddingLeft=a.box_padding_left.value+(isNum(a.box_padding_left.value)?a.box_padding_left_measurement.value:"")}if(a.box_margin_same.checked)b.style.margin=a.box_margin_top.value+(isNum(a.box_margin_top.value)?a.box_margin_top_measurement.value:"");else{b.style.marginTop=a.box_margin_top.value+(isNum(a.box_margin_top.value)?a.box_margin_top_measurement.value:"");b.style.marginRight=a.box_margin_right.value+
(isNum(a.box_margin_right.value)?a.box_margin_right_measurement.value:"");b.style.marginBottom=a.box_margin_bottom.value+(isNum(a.box_margin_bottom.value)?a.box_margin_bottom_measurement.value:"");b.style.marginLeft=a.box_margin_left.value+(isNum(a.box_margin_left.value)?a.box_margin_left_measurement.value:"")}if(a.border_style_same.checked)b.style.borderStyle=a.border_style_top.value;else{b.style.borderTopStyle=a.border_style_top.value;b.style.borderRightStyle=a.border_style_right.value;b.style.borderBottomStyle=
a.border_style_bottom.value;b.style.borderLeftStyle=a.border_style_left.value}if(a.border_width_same.checked)b.style.borderWidth=a.border_width_top.value+(isNum(a.border_width_top.value)?a.border_width_top_measurement.value:"");else{b.style.borderTopWidth=a.border_width_top.value+(isNum(a.border_width_top.value)?a.border_width_top_measurement.value:"");b.style.borderRightWidth=a.border_width_right.value+(isNum(a.border_width_right.value)?a.border_width_right_measurement.value:"");b.style.borderBottomWidth=
a.border_width_bottom.value+(isNum(a.border_width_bottom.value)?a.border_width_bottom_measurement.value:"");b.style.borderLeftWidth=a.border_width_left.value+(isNum(a.border_width_left.value)?a.border_width_left_measurement.value:"")}if(a.border_color_same.checked)b.style.borderColor=a.border_color_top.value;else{b.style.borderTopColor=a.border_color_top.value;b.style.borderRightColor=a.border_color_right.value;b.style.borderBottomColor=a.border_color_bottom.value;b.style.borderLeftColor=a.border_color_left.value}b.style.listStyleType=
a.list_type.value;b.style.listStylePosition=a.list_position.value;b.style.listStyleImage=a.list_bullet_image.value!=""?"url("+a.list_bullet_image.value+")":"";b.style.position=a.positioning_type.value;b.style.visibility=a.positioning_visibility.value;if(b.style.width=="")b.style.width=a.positioning_width.value+(isNum(a.positioning_width.value)?a.positioning_width_measurement.value:"");if(b.style.height=="")b.style.height=a.positioning_height.value+(isNum(a.positioning_height.value)?a.positioning_height_measurement.value:
"");b.style.zIndex=a.positioning_zindex.value;b.style.overflow=a.positioning_overflow.value;if(a.positioning_placement_same.checked){c=a.positioning_placement_top.value+(isNum(a.positioning_placement_top.value)?a.positioning_placement_top_measurement.value:"");b.style.top=c;b.style.right=c;b.style.bottom=c;b.style.left=c}else{b.style.top=a.positioning_placement_top.value+(isNum(a.positioning_placement_top.value)?a.positioning_placement_top_measurement.value:"");b.style.right=a.positioning_placement_right.value+
(isNum(a.positioning_placement_right.value)?a.positioning_placement_right_measurement.value:"");b.style.bottom=a.positioning_placement_bottom.value+(isNum(a.positioning_placement_bottom.value)?a.positioning_placement_bottom_measurement.value:"");b.style.left=a.positioning_placement_left.value+(isNum(a.positioning_placement_left.value)?a.positioning_placement_left_measurement.value:"")}if(a.positioning_clip_same.checked){c="rect(";a=isNum(a.positioning_clip_top.value)?a.positioning_clip_top.value+
a.positioning_clip_top_measurement.value:"auto";c+=a+" ";c+=a+" ";c+=a+" ";c+=a+")"}else{c="rect(";c+=(isNum(a.positioning_clip_top.value)?a.positioning_clip_top.value+a.positioning_clip_top_measurement.value:"auto")+" ";c+=(isNum(a.positioning_clip_right.value)?a.positioning_clip_right.value+a.positioning_clip_right_measurement.value:"auto")+" ";c+=(isNum(a.positioning_clip_bottom.value)?a.positioning_clip_bottom.value+a.positioning_clip_bottom_measurement.value:"auto")+" ";c+=isNum(a.positioning_clip_left.value)?
a.positioning_clip_left.value+a.positioning_clip_left_measurement.value:"auto";c+=")"}if(c!="rect(auto auto auto auto)")b.style.clip=c;b.style.cssText=b.style.cssText}function isNum(b){return RegExp("[0-9]+","g").test(b)}function showDisabledControls(){var b=document.forms,a,c;for(a=0;a<b.length;a++)for(c=0;c<b[a].elements.length;c++)b[a].elements[c].disabled?tinyMCEPopup.editor.dom.addClass(b[a].elements[c],"disabled"):tinyMCEPopup.editor.dom.removeClass(b[a].elements[c],"disabled")}
function fillSelect(b,a,c,e,d,f){b=document.forms[b];d=typeof d=="undefined"?";":d;f&&addSelectValue(b,a,"","");e=tinyMCEPopup.getParam(c,e).split(d);for(c=0;c<e.length;c++){f=false;if(e[c].charAt(0)=="+"){e[c]=e[c].substring(1);f=true}d=e[c].split("=");if(d.length>1){addSelectValue(b,a,d[0],d[1]);f&&selectByValue(b,a,d[1])}else{addSelectValue(b,a,d[0],d[0]);f&&selectByValue(b,a,d[0])}}}
function toggleSame(b,a){var c=document.forms[0].elements;if(b.checked){c[a+"_top"].disabled=false;c[a+"_right"].disabled=true;c[a+"_bottom"].disabled=true;c[a+"_left"].disabled=true;if(c[a+"_top_measurement"]){c[a+"_top_measurement"].disabled=false;c[a+"_right_measurement"].disabled=true;c[a+"_bottom_measurement"].disabled=true;c[a+"_left_measurement"].disabled=true}}else{c[a+"_top"].disabled=false;c[a+"_right"].disabled=false;c[a+"_bottom"].disabled=false;c[a+"_left"].disabled=false;if(c[a+"_top_measurement"]){c[a+
"_top_measurement"].disabled=false;c[a+"_right_measurement"].disabled=false;c[a+"_bottom_measurement"].disabled=false;c[a+"_left_measurement"].disabled=false}}showDisabledControls()}function synch(b,a){var c=document.forms[0];c.elements[a].value=c.elements[b].value;c.elements[b+"_measurement"]&&selectByValue(c,a+"_measurement",c.elements[b+"_measurement"].value)}tinyMCEPopup.onInit.add(init);
