# Generated by compass-jquery-plugin/gem-tasks/secret_sauce.rake
# Install with: compass install jquery/secret_sauce

file 'app/views/ui/_ui_form_error_messages.html.haml'
file 'app/views/ui/_ui_grid_for_without_block.js.haml'
file 'app/views/ui/_ui_static_dialog.html.haml'
file 'config/initializers/secret_sauce.rb'
javascript 'secret_sauce.js'
javascript 'secret_sauce.min.js'
stylesheet 'jquery.ui/secret_sauce.scss', :media => 'screen, projection'
