JQMOBILE_MESSAGE1 = "# Generated by compass-jquery-plugin/gem-tasks/jqmobilexx.rake\n# Install with: compass install jquery/jrails . --force\n\n"
JQMOBILE_MESSAGE2 = "// Generated by compass-jquery-plugin/gem-tasks/jqmobilesxx.rake\n"

class JqueryMobileTheme

  VARIABLE_NAME_BASE = 'ui_'
  VARIABLE_MATCHER = /(\S*)\/\*\{(\w*)\}\*\//

  attr_accessor :base_theme

  # Initialize with the base theme
  def initialize(base_theme_directory)
    @prefix = 'jquery.mobile'
    @theme_filename = "#{@prefix}.theme.css"
    @base_theme_directory = base_theme_directory
    @base_theme = File.read(File.join(@base_theme_directory, @theme_filename))
  end

  # This sets up the Regexp that will extract the variables from a theme
  def regexp
    return @regexp if @regexp
    placeholder = '___PLACEHOLDER___'
    @regexp = @base_theme.dup
    # Install placeholders for the variable data
    @regexp.gsub!(VARIABLE_MATCHER) {placeholder}
    # Strip the header comments
    @regexp.gsub! /.*^\*\/\s*/m, ''
    # Collapse all whitespace
    @regexp.gsub! /\s+/, ' '
    # Escape the literal strings
    @regexp = Regexp.escape(@regexp)
    # Whitespace means nothing
    @regexp.gsub! /\\\ /, '\s+'
    # Fast variable finder
    @regexp.gsub! placeholder, '([^;]*|\S*)'
    # Get 'er done
    @regexp = Regexp.new(@regexp)
  end

  # You can zip this with the regexp captures to create a variable hash
  def regexp_variables
    return @regexp_variables if @regexp_variables
    @regexp_variables = Array.new
    @base_theme.scan(VARIABLE_MATCHER) {@regexp_variables << $2}
    @regexp_variables
  end

  # Convert all the mobile.*.css files into sass goodness
  def convert_css(stylesheets)
    FileUtils.mkdir_p(File.join(stylesheets))
    Dir.foreach @base_theme_directory do |file|
      next unless /^#{@prefix}\..*\.css$/ =~ file
      next if ["{#{@prefix}.all.css", "#{@prefix}.base.css"].include? file
      css = File.read(File.join(@base_theme_directory, file))
      
      open File.join(stylesheets, '_' + file.gsub(/\.css$/,'.scss').gsub(/^#{@prefix}\./,'')), 'w' do |f|
        if file == @theme_filename
          f.print(self.class.theme_css2sass(@base_theme))
        else
          f.print(self.class.css2sass(css))
        end
        f.close
      end
    end
  end

  # Create a sass file of variables names and copy the images
  def convert_theme(name, dir, stylesheets)
    if name == 'base'
      theme = @base_theme
    else
      theme = File.read(File.join(dir, @theme_filename))
      
      # Fix Overlay stuff
      theme.gsub!(/\;filter:Alpha/, "; filter: Alpha")
      theme += WIDGET_BORDER
      theme += AUTOCOMPLETE_FIX
    end
    FileUtils.mkdir_p stylesheets
    # Figure out the variables with the regexp
    vars = Hash.new
    regexp.match(theme).captures.each_with_index do |capture, index|
      # Remove variable comments
      capture.gsub! /\/\*\{\w*\}\*\/$/, ''
      # Update url
      capture.gsub! /^url\(images(.*)\)/, "image_url(\"jquery.mobile/#{name}\\1\")"
      # Quote most things
      capture = "\"#{capture}\"" if capture =~ /[^#%0-9a-fptxm\-\.]/ and !(capture =~ /^image_url/) and !(capture =~ /^[A-Za-z]+/)
      vars[VARIABLE_NAME_BASE + regexp_variables[index]] ||= capture
    end
    # Write out the theme sass
    open File.join(stylesheets, "#{name}.scss"), 'w' do |f|
      f.print JQMOBILE_MESSAGE2
      f.print "\n"
      vars.each do |variable_name, value|
        f.print "$#{variable_name}: #{value} !default;\n"
      end
      f.print "\n@import \"jquery.mobile/_theme\"\n"
    end
  end

  # Converter for mobile.theme.css which has the variable names
  def self.theme_css2sass(theme_css)
    # Install variable names and convert to sass
    sass = css2sass(theme_css.gsub(VARIABLE_MATCHER){"$#{VARIABLE_NAME_BASE}#{$2}"})
    # Convert select lines from literal to programatic syntax
    sass.gsub!(/.*/){|x| /\!/=~x ? x.gsub(/:/,'=').gsub(/ solid /, ' "solid" ') : x}
    sass
  end

  # Sass is simply awesome
  def self.css2sass(css)
    sass = ''
    IO.popen("sass-convert -F scss -T scss", 'r+') { |f| f.print(css); f.close_write; sass = f.read }
    return sass
  end
end
