var ImageDialog={preInit:function(){var a;tinyMCEPopup.requireLangPack();if(a=tinyMCEPopup.getParam("external_image_list_url"))document.write('<script language="javascript" type="text/javascript" src="'+tinyMCEPopup.editor.documentBaseURI.toAbsolute(a)+'"><\/script>')},init:function(){var a=document.forms[0],b=tinyMCEPopup.editor;document.getElementById("srcbrowsercontainer").innerHTML=getBrowserHTML("srcbrowser","src","image","theme_advanced_image");if(isVisible("srcbrowser"))document.getElementById("src").style.width=
"180px";e=b.selection.getNode();this.fillFileList("image_list","tinyMCEImageList");if(e.nodeName=="IMG"){a.src.value=b.dom.getAttrib(e,"src");a.alt.value=b.dom.getAttrib(e,"alt");a.border.value=this.getAttrib(e,"border");a.vspace.value=this.getAttrib(e,"vspace");a.hspace.value=this.getAttrib(e,"hspace");a.width.value=b.dom.getAttrib(e,"width");a.height.value=b.dom.getAttrib(e,"height");a.insert.value=b.getLang("update");this.styleVal=b.dom.getAttrib(e,"style");selectByValue(a,"image_list",a.src.value);
selectByValue(a,"align",this.getAttrib(e,"align"));this.updateStyle()}},fillFileList:function(a,b){var c=tinyMCEPopup.dom,d=c.get(a);if((b=window[b])&&b.length>0){d.options[d.options.length]=new Option("","");tinymce.each(b,function(f){d.options[d.options.length]=new Option(f[0],f[1])})}else c.remove(c.getParent(a,"tr"))},update:function(){var a=document.forms[0],b=a.elements,c=tinyMCEPopup.editor,d={};tinyMCEPopup.restoreSelection();if(a.src.value===""){if(c.selection.getNode().nodeName=="IMG"){c.dom.remove(c.selection.getNode());
c.execCommand("mceRepaint")}}else{if(c.settings.inline_styles)d.style=this.styleVal;else d=tinymce.extend(d,{vspace:b.vspace.value,hspace:b.hspace.value,border:b.border.value,align:getSelectValue(a,"align")});tinymce.extend(d,{src:a.src.value.replace(/ /g,"%20"),alt:a.alt.value,width:a.width.value,height:a.height.value});if((a=c.selection.getNode())&&a.nodeName=="IMG"){c.dom.setAttribs(a,d);tinyMCEPopup.editor.execCommand("mceRepaint");tinyMCEPopup.editor.focus()}else{c.execCommand("mceInsertContent",
false,'<img id="__mce_tmp" />',{skip_undo:1});c.dom.setAttribs("__mce_tmp",d);c.dom.setAttrib("__mce_tmp","id","");c.undoManager.add()}}tinyMCEPopup.close()},updateStyle:function(){var a=tinyMCEPopup.dom,b,c,d=document.forms[0];if(tinyMCEPopup.editor.settings.inline_styles){b=tinyMCEPopup.dom.parseStyle(this.styleVal);if(c=getSelectValue(d,"align"))if(c=="left"||c=="right"){b["float"]=c;delete b["vertical-align"]}else{b["vertical-align"]=c;delete b["float"]}else{delete b["float"];delete b["vertical-align"]}if((c=
d.border.value)||c=="0")b.border=c=="0"?"0":c+"px solid black";else delete b.border;if(c=d.hspace.value){delete b.margin;b["margin-left"]=c+"px";b["margin-right"]=c+"px"}else{delete b["margin-left"];delete b["margin-right"]}if(c=d.vspace.value){delete b.margin;b["margin-top"]=c+"px";b["margin-bottom"]=c+"px"}else{delete b["margin-top"];delete b["margin-bottom"]}b=tinyMCEPopup.dom.parseStyle(a.serializeStyle(b),"img");this.styleVal=a.serializeStyle(b,"img")}},getAttrib:function(a,b){var c=tinyMCEPopup.editor,
d=c.dom,f;if(c.settings.inline_styles)switch(b){case "align":if(f=d.getStyle(a,"float"))return f;if(f=d.getStyle(a,"vertical-align"))return f;break;case "hspace":f=d.getStyle(a,"margin-left");c=d.getStyle(a,"margin-right");if(f&&f==c)return parseInt(f.replace(/[^0-9]/g,""));break;case "vspace":f=d.getStyle(a,"margin-top");c=d.getStyle(a,"margin-bottom");if(f&&f==c)return parseInt(f.replace(/[^0-9]/g,""));break;case "border":f=0;tinymce.each(["top","right","bottom","left"],function(g){g=d.getStyle(a,
"border-"+g+"-width");if(!g||g!=f&&f!==0){f=0;return false}if(g)f=g});if(f)return parseInt(f.replace(/[^0-9]/g,""))}if(f=d.getAttrib(a,b))return f;return""},resetImageData:function(){var a=document.forms[0];a.width.value=a.height.value=""},updateImageData:function(){var a=document.forms[0],b=ImageDialog;if(a.width.value=="")a.width.value=b.preloadImg.width;if(a.height.value=="")a.height.value=b.preloadImg.height},getImageData:function(){var a=document.forms[0];this.preloadImg=new Image;this.preloadImg.onload=
this.updateImageData;this.preloadImg.onerror=this.resetImageData;this.preloadImg.src=tinyMCEPopup.editor.documentBaseURI.toAbsolute(a.src.value)}};ImageDialog.preInit();tinyMCEPopup.onInit.add(ImageDialog.init,ImageDialog);
