# Generated by compass-jquery-plugin/gem-tasks/tools.rake
# Install with: compass install jquery/tools

file 'config/initializers/tools.rb'
javascript 'jquery.tools.js'
javascript 'jquery.tools.min.js'
javascript 'flowplayer.js'
javascript 'flowplayer.min.js'
javascript 'swfobject.js'
javascript 'swfobject.min.js'
