# Generated by compass-jquery-plugin/gem-tasks/jqtools.rake
# Install with: compass install jquery/jqtools

file 'config/initializers/jqtools.rb'
javascript 'jquery.tools.js'
javascript 'jquery.tools.min.js'
