(function(){var d=tinymce.DOM,z=tinymce.dom.Element,k=tinymce.dom.Event,A=tinymce.each,F=tinymce.is;tinymce.create("tinymce.plugins.InlinePopups",{init:function(a,e){a.onBeforeRenderUI.add(function(){a.windowManager=new tinymce.InlineWindowManager(a);d.loadCSS(e+"/skins/"+(a.settings.inlinepopups_skin||"clearlooks2")+"/window.css")})},getInfo:function(){return{longname:"InlinePopups",author:"Moxiecode Systems AB",authorurl:"http://tinymce.moxiecode.com",infourl:"http://wiki.moxiecode.com/index.php/TinyMCE:Plugins/inlinepopups",
version:tinymce.majorVersion+"."+tinymce.minorVersion}}});tinymce.create("tinymce.InlineWindowManager:tinymce.WindowManager",{InlineWindowManager:function(a){this.parent(a);this.zIndex=3E5;this.count=0;this.windows={}},open:function(a,e){var c=this,b,f="",t=c.editor,u=0,r=0,j,s;a=a||{};e=e||{};if(!a.inline)return c.parent(a,e);if((j=c._frontWindow())&&d.get(j.id+"_ifr"))j.focussedElement=d.get(j.id+"_ifr").contentWindow.document.activeElement;if(!a.type)c.bookmark=t.selection.getBookmark(1);b=d.uniqueId();
j=d.getViewPort();a.width=parseInt(a.width||320);a.height=parseInt(a.height||240)+(tinymce.isIE?8:0);a.min_width=parseInt(a.min_width||150);a.min_height=parseInt(a.min_height||100);a.max_width=parseInt(a.max_width||2E3);a.max_height=parseInt(a.max_height||2E3);a.left=a.left||Math.round(Math.max(j.x,j.x+j.w/2-a.width/2));a.top=a.top||Math.round(Math.max(j.y,j.y+j.h/2-a.height/2));a.movable=a.resizable=true;e.mce_width=a.width;e.mce_height=a.height;e.mce_inline=true;e.mce_window_id=b;e.mce_auto_focus=
a.auto_focus;c.features=a;c.params=e;c.onOpen.dispatch(c,a,e);if(a.type){f+=" mceModal";if(a.type)f+=" mce"+a.type.substring(0,1).toUpperCase()+a.type.substring(1);a.resizable=false}if(a.statusbar)f+=" mceStatusbar";if(a.resizable)f+=" mceResizable";if(a.minimizable)f+=" mceMinimizable";if(a.maximizable)f+=" mceMaximizable";if(a.movable)f+=" mceMovable";c._addAll(d.doc.body,["div",{id:b,role:"dialog","aria-labelledby":a.type?b+"_content":b+"_title","class":(t.settings.inlinepopups_skin||"clearlooks2")+
(tinymce.isIE&&window.getSelection?" ie9":""),style:"width:100px;height:100px"},["div",{id:b+"_wrapper","class":"mceWrapper"+f},["div",{id:b+"_top","class":"mceTop"},["div",{"class":"mceLeft"}],["div",{"class":"mceCenter"}],["div",{"class":"mceRight"}],["span",{id:b+"_title"},a.title||""]],["div",{id:b+"_middle","class":"mceMiddle"},["div",{id:b+"_left","class":"mceLeft",tabindex:"0"}],["span",{id:b+"_content"}],["div",{id:b+"_right","class":"mceRight",tabindex:"0"}]],["div",{id:b+"_bottom","class":"mceBottom"},
["div",{"class":"mceLeft"}],["div",{"class":"mceCenter"}],["div",{"class":"mceRight"}],["span",{id:b+"_status"},"Content"]],["a",{"class":"mceMove",tabindex:"-1",href:"javascript:;"}],["a",{"class":"mceMin",tabindex:"-1",href:"javascript:;",onmousedown:"return false;"}],["a",{"class":"mceMax",tabindex:"-1",href:"javascript:;",onmousedown:"return false;"}],["a",{"class":"mceMed",tabindex:"-1",href:"javascript:;",onmousedown:"return false;"}],["a",{"class":"mceClose",tabindex:"-1",href:"javascript:;",
onmousedown:"return false;"}],["a",{id:b+"_resize_n","class":"mceResize mceResizeN",tabindex:"-1",href:"javascript:;"}],["a",{id:b+"_resize_s","class":"mceResize mceResizeS",tabindex:"-1",href:"javascript:;"}],["a",{id:b+"_resize_w","class":"mceResize mceResizeW",tabindex:"-1",href:"javascript:;"}],["a",{id:b+"_resize_e","class":"mceResize mceResizeE",tabindex:"-1",href:"javascript:;"}],["a",{id:b+"_resize_nw","class":"mceResize mceResizeNW",tabindex:"-1",href:"javascript:;"}],["a",{id:b+"_resize_ne",
"class":"mceResize mceResizeNE",tabindex:"-1",href:"javascript:;"}],["a",{id:b+"_resize_sw","class":"mceResize mceResizeSW",tabindex:"-1",href:"javascript:;"}],["a",{id:b+"_resize_se","class":"mceResize mceResizeSE",tabindex:"-1",href:"javascript:;"}]]]);d.setStyles(b,{top:-1E4,left:-1E4});tinymce.isGecko&&d.setStyle(b,"overflow","auto");if(!a.type){u+=d.get(b+"_left").clientWidth;u+=d.get(b+"_right").clientWidth;r+=d.get(b+"_top").clientHeight;r+=d.get(b+"_bottom").clientHeight}d.setStyles(b,{top:a.top,
left:a.left,width:a.width+u,height:a.height+r});if(f=a.url||a.file){if(tinymce.relaxedDomain)f+=(f.indexOf("?")==-1?"?":"&")+"mce_rdomain="+tinymce.relaxedDomain;f=tinymce._addVer(f)}if(a.type){d.add(b+"_wrapper","a",{id:b+"_ok","class":"mceButton mceOk",href:"javascript:;",onmousedown:"return false;"},"Ok");a.type=="confirm"&&d.add(b+"_wrapper","a",{"class":"mceButton mceCancel",href:"javascript:;",onmousedown:"return false;"},"Cancel");d.add(b+"_middle","div",{"class":"mceIcon"});d.setHTML(b+"_content",
a.content.replace("\n","<br />"));k.add(b,"keyup",function(h){if(h.keyCode===27){a.button_func(false);return k.cancel(h)}});k.add(b,"keydown",function(h){var i;if(h.keyCode===9){(i=d.select("a.mceCancel",b+"_wrapper")[0])&&i!==h.target?i.focus():d.get(b+"_ok").focus();return k.cancel(h)}})}else{d.add(b+"_content","iframe",{id:b+"_ifr",src:'javascript:""',frameBorder:0,style:"border:0;width:10px;height:10px"});d.setStyles(b+"_ifr",{width:a.width,height:a.height});d.setAttrib(b+"_ifr","src",f)}f=k.add(b,
"mousedown",function(h){var i=h.target,g;g=c.windows[b];c.focus(b);if(i.nodeName=="A"||i.nodeName=="a")if(i.className=="mceMax"){g.oldPos=g.element.getXY();g.oldSize=g.element.getSize();h=d.getViewPort();h.w-=2;h.h-=2;g.element.moveTo(h.x,h.y);g.element.resizeTo(h.w,h.h);d.setStyles(b+"_ifr",{width:h.w-g.deltaWidth,height:h.h-g.deltaHeight});d.addClass(b+"_wrapper","mceMaximized")}else if(i.className=="mceMed"){g.element.moveTo(g.oldPos.x,g.oldPos.y);g.element.resizeTo(g.oldSize.w,g.oldSize.h);g.iframeElement.resizeTo(g.oldSize.w-
g.deltaWidth,g.oldSize.h-g.deltaHeight);d.removeClass(b+"_wrapper","mceMaximized")}else if(i.className=="mceMove")return c._startDrag(b,h,i.className);else if(d.hasClass(i,"mceResize"))return c._startDrag(b,h,i.className.substring(13))});s=k.add(b,"click",function(h){var i=h.target;c.focus(b);if(i.nodeName=="A"||i.nodeName=="a")switch(i.className){case "mceClose":c.close(null,b);return k.cancel(h);case "mceButton mceOk":case "mceButton mceCancel":a.button_func(i.className=="mceButton mceOk");return k.cancel(h)}});
k.add([b+"_left",b+"_right"],"focus",function(h){var i=d.get(b+"_ifr");if(i){i=d.select(":input:enabled,*[tabindex=0]",i.contentWindow.document.body);h.target.id===b+"_left"?i[i.length-1].focus():i[0].focus()}else d.get(b+"_ok").focus()});t=c.windows[b]={id:b,mousedown_func:f,click_func:s,element:new z(b,{blocker:1,container:t.getContainer()}),iframeElement:new z(b+"_ifr"),features:a,deltaWidth:u,deltaHeight:r};t.iframeElement.on("focus",function(){c.focus(b)});if(c.count==0&&c.editor.getParam("dialog_type",
"modal")=="modal"){d.add(d.doc.body,"div",{id:"mceModalBlocker","class":(c.editor.settings.inlinepopups_skin||"clearlooks2")+"_modalBlocker",style:{zIndex:c.zIndex-1}});d.show("mceModalBlocker");d.setAttrib(d.doc.body,"aria-hidden","true")}else d.setStyle("mceModalBlocker","z-index",c.zIndex-1);if(tinymce.isIE6||/Firefox\/2\./.test(navigator.userAgent)||tinymce.isIE&&!d.boxModel)d.setStyles("mceModalBlocker",{position:"absolute",left:j.x,top:j.y,width:j.w-2,height:j.h-2});d.setAttrib(b,"aria-hidden",
"false");c.focus(b);c._fixIELayout(b,1);d.get(b+"_ok")&&d.get(b+"_ok").focus();c.count++;return t},focus:function(a){var e;if(e=this.windows[a]){e.zIndex=this.zIndex++;e.element.setStyle("zIndex",e.zIndex);e.element.update();a+="_wrapper";d.removeClass(this.lastId,"mceFocus");d.addClass(a,"mceFocus");this.lastId=a;if(e.focussedElement)e.focussedElement.focus();else if(d.get(a+"_ok"))d.get(e.id+"_ok").focus();else d.get(e.id+"_ifr")&&d.get(e.id+"_ifr").focus()}},_addAll:function(a,e){var c;c=tinymce.DOM;
if(F(e,"string"))a.appendChild(c.doc.createTextNode(e));else if(e.length){a=a.appendChild(c.create(e[0],e[1]));for(c=2;c<e.length;c++)this._addAll(a,e[c])}},_startDrag:function(a,e,c){function b(){if(!j){f._fixIELayout(a,0);d.add(r.body,"div",{id:"mceEventBlocker","class":"mceEventBlocker "+(f.editor.settings.inlinepopups_skin||"clearlooks2"),style:{zIndex:f.zIndex+1}});if(tinymce.isIE6||tinymce.isIE&&!d.boxModel)d.setStyles("mceEventBlocker",{position:"absolute",left:l.x,top:l.y,width:l.w-2,height:l.h-
2});j=new z("mceEventBlocker");j.update();i=h.getXY();g=h.getSize();v=B.x+i.x-l.x;w=B.y+i.y-l.y;d.add(j.get(),"div",{id:"mcePlaceHolder","class":"mcePlaceHolder",style:{left:v,top:w,width:g.w,height:g.h}});C=new z("mcePlaceHolder")}}var f=this,t,u,r=d.doc,j,s=f.windows[a],h=s.element;h.getXY();var i,g,C,B,l,v,w,D,E,n,p,o,q;B={x:0,y:0};l=d.getViewPort();l.w-=2;l.h-=2;D=e.screenX;E=e.screenY;n=p=o=q=0;t=k.add(r,"mouseup",function(x){k.remove(r,"mouseup",t);k.remove(r,"mousemove",u);j&&j.remove();h.moveBy(n,
p);h.resizeBy(o,q);g=h.getSize();d.setStyles(a+"_ifr",{width:g.w-s.deltaWidth,height:g.h-s.deltaHeight});f._fixIELayout(a,1);return k.cancel(x)});c!="Move"&&b();u=k.add(r,"mousemove",function(x){var m,y;b();m=x.screenX-D;y=x.screenY-E;switch(c){case "ResizeW":n=m;o=0-m;break;case "ResizeE":o=m;break;case "ResizeN":case "ResizeNW":case "ResizeNE":if(c=="ResizeNW"){n=m;o=0-m}else if(c=="ResizeNE")o=m;p=y;q=0-y;break;case "ResizeS":case "ResizeSW":case "ResizeSE":if(c=="ResizeSW"){n=m;o=0-m}else if(c==
"ResizeSE")o=m;q=y;break;case "mceMove":n=m;p=y}if(o<(m=s.features.min_width-g.w)){if(n!==0)n+=o-m;o=m}if(q<(m=s.features.min_height-g.h)){if(p!==0)p+=q-m;q=m}o=Math.min(o,s.features.max_width-g.w);q=Math.min(q,s.features.max_height-g.h);n=Math.max(n,l.x-(v+l.x));p=Math.max(p,l.y-(w+l.y));n=Math.min(n,l.w+l.x-(v+g.w+l.x));p=Math.min(p,l.h+l.y-(w+g.h+l.y));if(n+p!==0){if(v+n<0)n=0;if(w+p<0)p=0;C.moveTo(v+n,w+p)}o+q!==0&&C.resizeTo(g.w+o,g.h+q);return k.cancel(x)});return k.cancel(e)},resizeBy:function(a,
e,c){if(c=this.windows[c]){c.element.resizeBy(a,e);c.iframeElement.resizeBy(a,e)}},close:function(a,e){var c,b=d.doc;e=this._findId(e||a);if(this.windows[e]){this.count--;if(this.count==0){d.remove("mceModalBlocker");d.setAttrib(d.doc.body,"aria-hidden","false");this.editor.focus()}if(c=this.windows[e]){this.onClose.dispatch(this);k.remove(b,"mousedown",c.mousedownFunc);k.remove(b,"click",c.clickFunc);k.clear(e);k.clear(e+"_ifr");d.setAttrib(e+"_ifr","src",'javascript:""');c.element.remove();delete this.windows[e];
(c=this._frontWindow())&&this.focus(c.id)}}else this.parent(a)},_frontWindow:function(){var a,e=0;A(this.windows,function(c){if(c.zIndex>e){a=c;e=c.zIndex}});return a},setTitle:function(a,e){var c;a=this._findId(a);if(c=d.get(a+"_title"))c.innerHTML=d.encode(e)},alert:function(a,e){var c=this,b;b=c.open({title:c,type:"alert",button_func:function(f){if(e)e.call(f||c,f);c.close(null,b.id)},content:d.encode(c.editor.getLang(a,a)),inline:1,width:400,height:130})},confirm:function(a,e){var c=this,b;b=
c.open({title:c,type:"confirm",button_func:function(f){if(e)e.call(f||c,f);c.close(null,b.id)},content:d.encode(c.editor.getLang(a,a)),inline:1,width:400,height:130})},_findId:function(a){if(typeof a=="string")return a;A(this.windows,function(e){var c=d.get(e.id+"_ifr");if(c&&a==c.contentWindow){a=e.id;return false}});return a},_fixIELayout:function(a,e){var c,b;if(tinymce.isIE6){A(["n","s","w","e","nw","ne","sw","se"],function(f){f=d.get(a+"_resize_"+f);d.setStyles(f,{width:e?f.clientWidth:"",height:e?
f.clientHeight:"",cursor:d.getStyle(f,"cursor",1)});d.setStyle(a+"_bottom","bottom","-1px")});if(c=this.windows[a]){c.element.hide();c.element.show();A(d.select("div,a",a),function(f){if(f.currentStyle.backgroundImage!="none"){b=new Image;b.src=f.currentStyle.backgroundImage.replace(/url\(\"(.+)\"\)/,"$1")}});d.get(a).style.filter=""}}}});tinymce.PluginManager.add("inlinepopups",tinymce.plugins.InlinePopups)})();
