require 'jquery/emulators'

ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :blackberry_landscape => ['compiled/emulators/blackberry.landscape.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :blackberry_portrait => ['compiled/emulators/blackberry.portrait.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :galaxy_s_landscape => ['compiled/emulators/galaxy.s.landscape.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :galaxy_s_portrait => ['compiled/emulators/galaxy.s.portrait.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :galaxy_s2_landscape => ['compiled/emulators/galaxy.s2.landscape.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :galaxy_s2_portrait => ['compiled/emulators/galaxy.s2.portrait.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :galaxy7_landscape => ['compiled/emulators/galaxy.tab.7.landscape.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :galaxy7_portrait => ['compiled/emulators/galaxy.tab.7.portrait.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :galaxy10_landscape => ['compiled/emulators/galaxy.tab.10.1.landscape.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :galaxy10_portrait => ['compiled/emulators/galaxy.tab.10.1.portrait.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :ipad_landscape => ['compiled/emulators/ipad.landscape.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :ipad_portrait => ['compiled/emulators/ipad.portrait.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :iphone3_landscape => ['compiled/emulators/iphone.3.landscape.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :iphone3_portrait => ['compiled/emulators/iphone.3.portrait.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :iphone4_landscape => ['compiled/emulators/iphone.4.landscape.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :iphone4_portrait => ['compiled/emulators/iphone.4.portrait.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :palm_landscape => ['compiled/emulators/palm.landscape.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :palm_portrait => ['compiled/emulators/palm.portrait.css']
