(function(){function E(a){var i,c;if(a&&!a.splice){i=[];for(c=0;;c++)if(a[c])i[c]=a[c];else break;return i}return a}var y=tinymce.explode("id,name,width,height,style,align,class,hspace,vspace,bgcolor,type"),C=tinymce.makeMap(y.join(",")),t=tinymce.html.Node,A,B,z=tinymce.util.JSON;A=[["Flash","d27cdb6e-ae6d-11cf-96b8-444553540000","application/x-shockwave-flash","http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"],["ShockWave","166b1bca-3f9c-11cf-8075-444553540000",
"application/x-director","http://download.macromedia.com/pub/shockwave/cabs/director/sw.cab#version=8,5,1,0"],["WindowsMedia","6bf52a52-394a-11d3-b153-00c04f79faa6,22d6f312-b0f6-11d0-94ab-0080c74c7e95,05589fa1-c356-11ce-bf01-00aa0055595a","application/x-mplayer2","http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=5,1,52,701"],["QuickTime","02bf25d5-8c17-4b23-bc80-d3488abddc6b","video/quicktime","http://www.apple.com/qtactivex/qtplugin.cab#version=6,0,2,0"],["RealMedia",
"cfcdaa03-8be4-11cf-b84b-0020afbbccfa","audio/x-pn-realaudio-plugin","http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"],["Java","8ad9c840-044e-11d1-b3e9-00805f499d93","application/x-java-applet","http://java.sun.com/products/plugin/autodl/jinstall-1_5_0-windows-i586.cab#Version=1,5,0,0"],["Silverlight","dfeaf541-f3e1-4c24-acac-99c30715084a","application/x-silverlight-2"],["Iframe"],["Video"]];tinymce.create("tinymce.plugins.MediaPlugin",{init:function(a,i){function c(d){return d&&
d.nodeName==="IMG"&&a.dom.hasClass(d,"mceItemMedia")}var e=this,j={},l,m,f,n;e.editor=a;e.url=i;B="";for(l=0;l<A.length;l++){n=A[l][0];f={name:n,clsids:tinymce.explode(A[l][1]||""),mimes:tinymce.explode(A[l][2]||""),codebase:A[l][3]};for(m=0;m<f.clsids.length;m++)j["clsid:"+f.clsids[m]]=f;for(m=0;m<f.mimes.length;m++)j[f.mimes[m]]=f;j["mceItem"+n]=f;j[n.toLowerCase()]=f;B+=(B?"|":"")+n}tinymce.each(a.getParam("media_types","video=mp4,m4v,ogv,webm;silverlight=xap;flash=swf,flv;shockwave=dcr;quicktime=mov,qt,mpg,mp3,mpeg;shockwave=dcr;windowsmedia=avi,wmv,wm,asf,asx,wmx,wvx;realmedia=rm,ra,ram;java=jar").split(";"),
function(d){var b,h,k;d=d.split(/=/);h=tinymce.explode(d[1].toLowerCase());for(b=0;b<h.length;b++)if(k=j[d[0].toLowerCase()])j[h[b]]=k});B=RegExp("write("+B+")\\(([^)]+)\\)");e.lookup=j;a.onPreInit.add(function(){a.schema.addValidElements("object[id|style|width|height|classid|codebase|*],param[name|value],embed[id|style|width|height|type|src|*],video[*],audio[*],source[*]");a.parser.addNodeFilter("object,embed,video,audio,script,iframe",function(d){for(var b=d.length;b--;)e.objectToImg(d[b])});a.serializer.addNodeFilter("img",
function(d,b,h){b=d.length;for(var k;b--;){k=d[b];if((k.attr("class")||"").indexOf("mceItemMedia")!==-1)e.imgToObject(k,h)}})});a.onInit.add(function(){a.theme&&a.theme.onResolveName&&a.theme.onResolveName.add(function(d,b){if(b.name==="img"&&a.dom.hasClass(b.node,"mceItemMedia"))b.name="media"});a&&a.plugins.contextmenu&&a.plugins.contextmenu.onContextMenu.add(function(d,b,h){h.nodeName==="IMG"&&h.className.indexOf("mceItemMedia")!==-1&&b.add({title:"media.edit",icon:"media",cmd:"mceMedia"})})});
a.addCommand("mceMedia",function(){var d,b;b=a.selection.getNode();if(c(b)){d=z.parse(a.dom.getAttrib(b,"data-mce-json"));tinymce.each(y,function(h){var k=a.dom.getAttrib(b,h);if(k)d[h]=k});d.type=e.getType(b.className).name.toLowerCase()}d||(d={type:"flash",video:{sources:[]},params:{}});a.windowManager.open({file:i+"/media.htm",width:430+parseInt(a.getLang("media.delta_width",0)),height:500+parseInt(a.getLang("media.delta_height",0)),inline:1},{plugin_url:i,data:d})});a.addButton("media",{title:"media.desc",
cmd:"mceMedia"});a.onNodeChange.add(function(d,b,h){b.setActive("media",c(h))})},convertUrl:function(a,i){var c=this.editor,e=c.settings,j=e.url_converter;e=e.url_converter_scope||this;if(!a)return a;if(i)return c.documentBaseURI.toAbsolute(a);return j.call(e,a,"src","object")},getInfo:function(){return{longname:"Media",author:"Moxiecode Systems AB",authorurl:"http://tinymce.moxiecode.com",infourl:"http://wiki.moxiecode.com/index.php/TinyMCE:Plugins/media",version:tinymce.majorVersion+"."+tinymce.minorVersion}},
dataToImg:function(a,i){var c,e;a.params.src=this.convertUrl(a.params.src,i);if(c=a.video.attrs)c.src=this.convertUrl(c.src,i);if(c)c.poster=this.convertUrl(c.poster,i);if(c=E(a.video.sources))for(e=0;e<c.length;e++)c[e].src=this.convertUrl(c[e].src,i);c=this.editor.dom.create("img",{id:a.id,style:a.style,align:a.align,src:this.editor.theme.url+"/img/trans.gif","class":"mceItemMedia mceItem"+this.getType(a.type).name,"data-mce-json":z.serialize(a,"'")});c.width=a.width||"320";c.height=a.height||"240";
return c},dataToHtml:function(a,i){return this.editor.serializer.serialize(this.dataToImg(a,i),{force_absolute:i})},htmlToData:function(a){var i,c;c={type:"flash",video:{sources:[]},params:{}};if(i=this.editor.parser.parse(a).getAll("img")[0]){c=z.parse(i.attr("data-mce-json"));c.type=this.getType(i.attr("class")).name.toLowerCase();tinymce.each(y,function(e){var j=i.attr(e);if(j)c[e]=j})}return c},getType:function(a){var i,c;i=tinymce.explode(a," ");for(a=0;a<i.length;a++)if(c=this.lookup[i[a]])return c},
imgToObject:function(a,i){function c(o,q){var s,v,F;if(F=j.getParam("flash_video_player_url",e.convertUrl(e.url+"/moxieplayer.swf"))){s=j.documentBaseURI;b.params.src=F;if(j.getParam("flash_video_player_absvideourl",true)){o=s.toAbsolute(o||"",true);q=s.toAbsolute(q||"",true)}v="";s=j.getParam("flash_video_player_flashvars",{url:"$url",poster:"$poster"});tinymce.each(s,function(x,D){x=x.replace(/\$url/,o||"");x=x.replace(/\$poster/,q||"");if(x.length>0)v+=(v?"&":"")+D+"="+escape(x)});if(v.length)b.params.flashvars=
v;s=j.getParam("flash_video_player_params",{allowfullscreen:true,allowscriptaccess:true});tinymce.each(s,function(x,D){b.params[D]=""+x})}}var e=this,j=e.editor,l,m,f,n,d,b,h,k,p,w,g,u,r;b=z.parse(a.attr("data-mce-json"));k=this.getType(a.attr("class"));r=a.attr("data-mce-style");if(!r)if(r=a.attr("style"))r=j.dom.serializeStyle(j.dom.parseStyle(r,"img"));if(k.name==="Iframe"){g=new t("iframe",1);tinymce.each(y,function(o){var q=a.attr(o);if(o=="class"&&q)q=q.replace(/mceItem.+ ?/g,"");q&&q.length>
0&&g.attr(o,q)});for(n in b.params)g.attr(n,b.params[n]);g.attr({style:r,src:b.params.src});a.replace(g)}else if(this.editor.settings.media_use_script){g=(new t("script",1)).attr("type","text/javascript");d=new t("#text",3);d.value="write"+k.name+"("+z.serialize(tinymce.extend(b.params,{width:a.attr("width"),height:a.attr("height")}))+");";g.append(d);a.replace(g)}else{if(k.name==="Video"&&b.video.sources[0]){l=(new t("video",1)).attr(tinymce.extend({id:a.attr("id"),width:a.attr("width"),height:a.attr("height"),
style:r},b.video.attrs));if(b.video.attrs)u=b.video.attrs.poster;h=b.video.sources=E(b.video.sources);for(p=0;p<h.length;p++)if(/\.mp4$/.test(h[p].src))w=h[p].src;if(!h[0].type){l.attr("src",h[0].src);h.splice(0,1)}for(p=0;p<h.length;p++){d=(new t("source",1)).attr(h[p]);d.shortEnded=true;l.append(d)}if(w){c(w,u);k=e.getType("flash")}else b.params.src=""}if(b.params.src){/\.flv$/i.test(b.params.src)&&c(b.params.src,"");if(i&&i.force_absolute)b.params.src=j.documentBaseURI.toAbsolute(b.params.src);
m=(new t("object",1)).attr({id:a.attr("id"),width:a.attr("width"),height:a.attr("height"),style:r});tinymce.each(y,function(o){b[o]&&o!="type"&&m.attr(o,b[o])});for(n in b.params){h=new t("param",1);h.shortEnded=true;d=b.params[n];if(n==="src"&&k.name==="WindowsMedia")n="url";h.attr({name:n,value:d});m.append(h)}if(this.editor.getParam("media_strict",true))m.attr({data:b.params.src,type:k.mimes[0]});else{m.attr({classid:"clsid:"+k.clsids[0],codebase:k.codebase});f=new t("embed",1);f.shortEnded=true;
f.attr({id:a.attr("id"),width:a.attr("width"),height:a.attr("height"),style:r,type:k.mimes[0]});for(n in b.params)f.attr(n,b.params[n]);tinymce.each(y,function(o){b[o]&&o!="type"&&f.attr(o,b[o])});m.append(f)}if(b.object_html){d=new t("#text",3);d.raw=true;d.value=b.object_html;m.append(d)}l&&l.append(m)}if(l)if(b.video_html){d=new t("#text",3);d.raw=true;d.value=b.video_html;l.append(d)}l||m?a.replace(l||m):a.remove()}},objectToImg:function(a){function i(v){return(new tinymce.html.Serializer({inner:true,
validate:false})).serialize(v)}var c,e,j,l,m,f,n,d,b,h,k,p,w,g,u,r=this.lookup,o,q=this.editor.settings.url_converter,s=this.editor.settings.url_converter_scope;if(a.parent){if(a.name==="script"){if(a.firstChild)f=B.exec(a.firstChild.value);if(!f)return;u=f[1];g={video:{},params:z.parse(f[2])};d=g.params.width;b=g.params.height}g=g||{video:{},params:{}};m=new t("img",1);m.attr({src:this.editor.theme.url+"/img/trans.gif"});f=a.name;if(f==="video"){j=a;c=a.getAll("object")[0];e=a.getAll("embed")[0];
d=j.attr("width");b=j.attr("height");n=j.attr("id");g.video={attrs:{},sources:[]};o=g.video.attrs;for(f in j.attributes.map)o[f]=j.attributes.map[f];(p=a.attr("src"))&&g.video.sources.push({src:q.call(s,p,"src","video")});w=j.getAll("source");for(k=0;k<w.length;k++){p=w[k].remove();g.video.sources.push({src:q.call(s,p.attr("src"),"src","source"),type:p.attr("type"),media:p.attr("media")})}if(o.poster)o.poster=q.call(s,o.poster,"poster","video")}if(a.name==="object"){c=a;e=a.getAll("embed")[0]}if(a.name===
"embed")e=a;if(a.name==="iframe"){l=a;u="Iframe"}if(c){d=d||c.attr("width");b=b||c.attr("height");h=h||c.attr("style");n=n||c.attr("id");w=c.getAll("param");for(k=0;k<w.length;k++){p=w[k];f=p.remove().attr("name");C[f]||(g.params[f]=p.attr("value"))}g.params.src=g.params.src||c.attr("data")}if(e){d=d||e.attr("width");b=b||e.attr("height");h=h||e.attr("style");n=n||e.attr("id");for(f in e.attributes.map)if(!C[f]&&!g.params[f])g.params[f]=e.attributes.map[f]}if(l){d=l.attr("width");b=l.attr("height");
h=h||l.attr("style");n=l.attr("id");tinymce.each(y,function(v){m.attr(v,l.attr(v))});for(f in l.attributes.map)if(!C[f]&&!g.params[f])g.params[f]=l.attributes.map[f]}if(g.params.movie){g.params.src=g.params.src||g.params.movie;delete g.params.movie}if(g.params.src)g.params.src=q.call(s,g.params.src,"src","object");if(j)u=r.video.name;if(c&&!u)u=(r[(c.attr("clsid")||"").toLowerCase()]||r[(c.attr("type")||"").toLowerCase()]||{}).name;if(e&&!u)u=(r[(e.attr("type")||"").toLowerCase()]||{}).name;a.replace(m);
e&&e.remove();if(c)if(a=i(c.remove()))g.object_html=a;if(j)if(a=i(j.remove()))g.video_html=a;m.attr({id:n,"class":"mceItemMedia mceItem"+(u||"Flash"),style:h,width:d||"320",height:b||"240","data-mce-json":z.serialize(g,"'")})}}});tinymce.PluginManager.add("media",tinymce.plugins.MediaPlugin)})();
