tinyMCEPopup.requireLangPack();
var doc,defaultDocTypes='XHTML 1.0 Transitional=<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">,XHTML 1.0 Frameset=<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">,XHTML 1.0 Strict=<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">,XHTML 1.1=<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">,HTML 4.01 Transitional=<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">,HTML 4.01 Strict=<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">,HTML 4.01 Frameset=<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">',defaultEncodings=
"Western european (iso-8859-1)=iso-8859-1,Central European (iso-8859-2)=iso-8859-2,Unicode (UTF-8)=utf-8,Chinese traditional (Big5)=big5,Cyrillic (iso-8859-5)=iso-8859-5,Japanese (iso-2022-jp)=iso-2022-jp,Greek (iso-8859-7)=iso-8859-7,Korean (iso-2022-kr)=iso-2022-kr,ASCII (us-ascii)=us-ascii",defaultMediaTypes="all=all,screen=screen,print=print,tty=tty,tv=tv,projection=projection,handheld=handheld,braille=braille,aural=aural",defaultFontNames="Arial=arial,helvetica,sans-serif;Courier New=courier new,courier,monospace;Georgia=georgia,times new roman,times,serif;Tahoma=tahoma,arial,helvetica,sans-serif;Times New Roman=times new roman,times,serif;Verdana=verdana,arial,helvetica,sans-serif;Impact=impact;WingDings=wingdings",
defaultFontSizes="10px,11px,12px,13px,14px,15px,16px";
function init(){var c=document.forms.fullpage,b=c.elements,d,a,e,g,i=tinyMCEPopup.editor,l=tinyMCEPopup.dom;g=i.getParam("fullpage_doctypes",defaultDocTypes).split(",");for(a=0;a<g.length;a++){e=g[a].split("=");e.length>1&&addSelectValue(c,"doctypes",e[0],e[1])}g=i.getParam("fullpage_fonts",defaultFontNames).split(";");for(a=0;a<g.length;a++){e=g[a].split("=");e.length>1&&addSelectValue(c,"fontface",e[0],e[1])}g=i.getParam("fullpage_fontsizes",defaultFontSizes).split(",");for(a=0;a<g.length;a++)addSelectValue(c,
"fontsize",g[a],g[a]);g=i.getParam("fullpage_media_types",defaultMediaTypes).split(",");for(a=0;a<g.length;a++){e=g[a].split("=");if(e.length>1){addSelectValue(c,"element_style_media",e[0],e[1]);addSelectValue(c,"element_link_media",e[0],e[1])}}g=i.getParam("fullpage_encodings",defaultEncodings).split(",");for(a=0;a<g.length;a++){e=g[a].split("=");if(e.length>1){addSelectValue(c,"docencoding",e[0],e[1]);addSelectValue(c,"element_script_charset",e[0],e[1]);addSelectValue(c,"element_link_charset",e[0],
e[1])}}document.getElementById("bgcolor_pickcontainer").innerHTML=getColorPickerHTML("bgcolor_pick","bgcolor");document.getElementById("link_color_pickcontainer").innerHTML=getColorPickerHTML("link_color_pick","link_color");document.getElementById("visited_color_pickcontainer").innerHTML=getColorPickerHTML("visited_color_pick","visited_color");document.getElementById("active_color_pickcontainer").innerHTML=getColorPickerHTML("active_color_pick","active_color");document.getElementById("textcolor_pickcontainer").innerHTML=
getColorPickerHTML("textcolor_pick","textcolor");document.getElementById("stylesheet_browsercontainer").innerHTML=getBrowserHTML("stylesheetbrowser","stylesheet","file","fullpage");document.getElementById("link_href_pickcontainer").innerHTML=getBrowserHTML("link_href_browser","element_link_href","file","fullpage");document.getElementById("script_src_pickcontainer").innerHTML=getBrowserHTML("script_src_browser","element_script_src","file","fullpage");document.getElementById("bgimage_pickcontainer").innerHTML=
getBrowserHTML("bgimage_browser","bgimage","image","fullpage");if(isVisible("stylesheetbrowser"))document.getElementById("stylesheet").style.width="220px";if(isVisible("link_href_browser"))document.getElementById("element_link_href").style.width="230px";if(isVisible("bgimage_browser"))document.getElementById("bgimage").style.width="210px";l.add(document.body,"iframe",{id:"documentIframe",src:'javascript:""',style:{display:"none"}});doc=l.get("documentIframe").contentWindow.document;h=tinyMCEPopup.getWindowArg("head_html");
h=h.replace(/<script>/gi,'<script type="text/javascript">');h=h.replace(/type=([\"\'])?/gi,"type=$1-mce-");h=h.replace(/(src=|href=)/g,"data-mce-$1");doc.write(h+"</body></html>");doc.close();xmlVer=getReItem(/<\?\s*?xml.*?version\s*?=\s*?"(.*?)".*?\?>/gi,h,1);xmlEnc=getReItem(/<\?\s*?xml.*?encoding\s*?=\s*?"(.*?)".*?\?>/gi,h,1);docType=getReItem(/<\!DOCTYPE.*?>/gi,h.replace(/\n/g,""),0).replace(/ +/g," ");c.langcode.value=getReItem(/lang="(.*?)"/gi,h,1);a=getReItem(/dir\s*=\s*["']([^"']*)["']/i,
h,1);if(doc.body.hasAttribute("dir")&&doc.body.getAttribute("dir")!="")a=doc.body.getAttribute("dir");if(d=doc.getElementsByTagName("title")[0])b.metatitle.value=d.textContent||d.text;tinymce.each(doc.getElementsByTagName("meta"),function(f){var j=(f.getAttribute("name",2)||"").toLowerCase(),k=f.getAttribute("content",2);f=f.getAttribute("httpEquiv",2)||"";d=b["meta"+j];if(j=="robots")selectByValue(c,"metarobots",tinymce.trim(k),true,true);else{switch(f.toLowerCase()){case "content-type":tmp=getReItem(/charset\s*=\s*(.*)\s*/gi,
k,1);if(tmp!="")xmlEnc=tmp;return}if(d)d.value=k}});selectByValue(c,"doctypes",docType,true,true);selectByValue(c,"docencoding",xmlEnc,true,true);selectByValue(c,"langdir",a,true,true);if(xmlVer!="")b.xml_pi.checked=true;tinymce.each(doc.getElementsByTagName("link"),function(f){var j=f.getAttribute("media",2)||"";if((f.getAttribute("type",2)||"")=="-mce-text/css"&&(j==""||j=="screen"||j=="all")&&(f.getAttribute("rel",2)||"")=="stylesheet"){c.stylesheet.value=f.getAttribute("data-mce-href",2)||"";
return false}});tinymce.each(doc.getElementsByTagName("style"),function(f){f=parseStyleElement(f);for(x=0;x<f.length;x++){if(f[x].rule.indexOf("a:visited")!=-1&&f[x].data.color)c.visited_color.value=f[x].data.color;if(f[x].rule.indexOf("a:link")!=-1&&f[x].data.color)c.link_color.value=f[x].data.color;if(f[x].rule.indexOf("a:active")!=-1&&f[x].data.color)c.active_color.value=f[x].data.color}});c.textcolor.value=tinyMCEPopup.dom.getAttrib(doc.body,"text");c.active_color.value=tinyMCEPopup.dom.getAttrib(doc.body,
"alink");c.link_color.value=tinyMCEPopup.dom.getAttrib(doc.body,"link");c.visited_color.value=tinyMCEPopup.dom.getAttrib(doc.body,"vlink");c.bgcolor.value=tinyMCEPopup.dom.getAttrib(doc.body,"bgcolor");c.bgimage.value=tinyMCEPopup.dom.getAttrib(doc.body,"background");a=tinyMCEPopup.dom.parseStyle(tinyMCEPopup.dom.getAttrib(doc.body,"style"));a["font-family"]?selectByValue(c,"fontface",a["font-family"],true,true):selectByValue(c,"fontface",i.getParam("fullpage_default_fontface",""),true,true);a["font-size"]?
selectByValue(c,"fontsize",a["font-size"],true,true):selectByValue(c,"fontsize",i.getParam("fullpage_default_fontsize",""),true,true);if(a.color)c.textcolor.value=convertRGBToHex(a.color);if(a["background-image"])c.bgimage.value=a["background-image"].replace(RegExp("url\\('?([^']*)'?\\)","gi"),"$1");if(a["background-color"])c.bgcolor.value=a["background-color"];if(a.margin){tmp=a.margin.replace(/[^0-9 ]/g,"");tmp=tmp.split(/ +/);c.topmargin.value=tmp.length>0?tmp[0]:"";c.rightmargin.value=tmp.length>
1?tmp[1]:tmp[0];c.bottommargin.value=tmp.length>2?tmp[2]:tmp[0];c.leftmargin.value=tmp.length>3?tmp[3]:tmp[0]}if(a["margin-left"])c.leftmargin.value=a["margin-left"].replace(/[^0-9]/g,"");if(a["margin-right"])c.rightmargin.value=a["margin-right"].replace(/[^0-9]/g,"");if(a["margin-top"])c.topmargin.value=a["margin-top"].replace(/[^0-9]/g,"");if(a["margin-bottom"])c.bottommargin.value=a["margin-bottom"].replace(/[^0-9]/g,"");c.style.value=tinyMCEPopup.dom.serializeStyle(a);updateColor("textcolor_pick",
"textcolor");updateColor("bgcolor_pick","bgcolor");updateColor("visited_color_pick","visited_color");updateColor("active_color_pick","active_color");updateColor("link_color_pick","link_color")}function getReItem(c,b,d){if((c=c.exec(b))&&c.length>d)return c[d];return""}
function updateAction(){function c(f,j,k){k=""+k;k.length>0?f.setAttribute(j,k):f.removeAttribute(j,k)}var b=document.forms[0],d,a,e,g,i,l;g=doc.getElementsByTagName("head")[0];d=doc.getElementsByTagName("script");for(a=0;a<d.length;a++)tinyMCEPopup.dom.getAttrib(d[a],"data-mce-type")==""&&d[a].setAttribute("mce-type","text/javascript");d=doc.getElementsByTagName("link");for(a=0;a<d.length;a++){i=d[a];l=tinyMCEPopup.dom.getAttrib(i,"media");if(tinyMCEPopup.dom.getAttrib(i,"data-mce-type")=="text/css"&&
(l==""||l=="screen"||l=="all")&&tinyMCEPopup.dom.getAttrib(i,"rel")=="stylesheet"){b.stylesheet.value==""?i.parentNode.removeChild(i):i.setAttribute("data-mce-href",b.stylesheet.value);break}}if(b.stylesheet.value!=""){i=doc.createElement("link");i.setAttribute("type","text/css");i.setAttribute("data-mce-href",b.stylesheet.value);i.setAttribute("rel","stylesheet");g.appendChild(i)}setMeta(g,"keywords",b.metakeywords.value);setMeta(g,"description",b.metadescription.value);setMeta(g,"author",b.metaauthor.value);
setMeta(g,"copyright",b.metacopyright.value);setMeta(g,"robots",getSelectValue(b,"metarobots"));setMeta(g,"Content-Type",getSelectValue(b,"docencoding"));c(doc.body,"dir",getSelectValue(b,"langdir"));doc.body.style.cssText=b.style.value;c(doc.body,"vLink",b.visited_color.value);c(doc.body,"link",b.link_color.value);c(doc.body,"text",b.textcolor.value);c(doc.body,"aLink",b.active_color.value);doc.body.style.fontFamily=getSelectValue(b,"fontface");doc.body.style.fontSize=getSelectValue(b,"fontsize");
doc.body.style.backgroundColor=b.bgcolor.value;if(b.leftmargin.value!="")doc.body.style.marginLeft=b.leftmargin.value+"px";if(b.rightmargin.value!="")doc.body.style.marginRight=b.rightmargin.value+"px";if(b.bottommargin.value!="")doc.body.style.marginBottom=b.bottommargin.value+"px";if(b.topmargin.value!="")doc.body.style.marginTop=b.topmargin.value+"px";d=doc.getElementsByTagName("html")[0];c(d,"lang",b.langcode.value);c(d,"xml:lang",b.langcode.value);doc.body.style.backgroundImage=b.bgimage.value!=
""?"url('"+b.bgimage.value+"')":"";d=tinyMCEPopup.editor.plugins.fullpage._createSerializer();d.setRules("-title,meta[http-equiv|name|content],base[href|target],link[href|rel|type|title|media],style[type],script[type|language|src],html[lang|xml::lang|xmlns],body[style|dir|vlink|link|text|alink],head");d=d.serialize(doc.documentElement);d=d.substring(0,d.lastIndexOf("</body>"));d=d.indexOf("<title>")==-1?d.replace(/<head.*?>/,"$&\n<title>"+tinyMCEPopup.dom.encode(b.metatitle.value)+"</title>"):d.replace(/<title>(.*?)<\/title>/,
"<title>"+tinyMCEPopup.dom.encode(b.metatitle.value)+"</title>");htmlt=(e=b.langcode.value)?'<html lang="'+e+'" xml:lang="'+e+'">':"<html>";d=d.replace(/<html.*?>/,htmlt);if((e=getSelectValue(b,"doctypes"))!="")d=e+"\n"+d;if(b.xml_pi.checked){a='<?xml version="1.0"';if((e=getSelectValue(b,"docencoding"))!="")a+=' encoding="'+e+'"';a+="?>\n";d=a+d}d=d.replace(/type=\"\-mce\-/gi,'type="');tinyMCEPopup.editor.plugins.fullpage.head=d;tinyMCEPopup.editor.plugins.fullpage._setBodyAttribs(tinyMCEPopup.editor,
{});tinyMCEPopup.close()}function changedStyleField(){}
function setMeta(c,b,d){var a,e;a=c.getElementsByTagName("meta");for(e=0;e<a.length;e++){if(b=="Content-Type"&&tinyMCEPopup.dom.getAttrib(a[e],"http-equiv")==b){d==""?a[e].parentNode.removeChild(a[e]):a[e].setAttribute("content","text/html; charset="+d);return}if(tinyMCEPopup.dom.getAttrib(a[e],"name")==b){d==""?a[e].parentNode.removeChild(a[e]):a[e].setAttribute("content",d);return}}if(d!=""){a=doc.createElement("meta");if(b=="Content-Type")a.httpEquiv=b;else a.setAttribute("name",b);a.setAttribute("content",
d);c.appendChild(a)}}function parseStyleElement(c){var b=c.innerHTML,d;b=b.replace(/<!--/gi,"");b=b.replace(/--\>/gi,"");b=b.replace(/[\n\r]/gi,"");b=b.replace(/\s+/gi," ");c=[];b=b.split(/{|}/);for(d=0;d<b.length;d+=2)if(b[d]!="")c[c.length]={rule:tinymce.trim(b[d]),data:tinyMCEPopup.dom.parseStyle(b[d+1])};return c}
function serializeStyleElement(c){var b,d,a;d="<!--\n";for(b=0;b<c.length;b++){d+=c[b].rule+" {\n";a=tinyMCE.serializeStyle(c[b].data);if(a!="")a+=";";d+=a.replace(/;/g,";\n");d+="}\n";if(b!=c.length-1)d+="\n"}d+="\n--\>";return d}tinyMCEPopup.onInit.add(init);
