# Generated by compass-jquery-plugin/gem-tasks/jqical.rake
# Install with: compass install jquery/jqical

file 'config/initializers/calendar.rb'
javascript 'jquery.calendar.js'
javascript 'jquery.calendar.min.js'
stylesheet 'jquery.ui/calendar.scss'
