# Generated by compass-jquery-plugin/gem-tasks/jqical.rake
# Install with: compass install jquery/jqical

file 'config/initializers/jqical.rb'
javascript 'jquery.jqical.js'
javascript 'jquery.jqical.min.js'
stylesheet 'jquery.ui/jqical.scss'
image 'jquery.ui/jqical/calendar.png'
image 'jquery.ui/jqical/clock.png'
