# Generated by compass-jquery-plugin/gem-tasks/jqical.rake
# Install with: compass install jquery/jqical

file 'app/views/shared/_ui_event_for.js.haml'
file 'config/initializers/jqical.rb'
javascript 'jquery.jqical.js'
javascript 'jquery.jqical.min.js'
stylesheet 'jquery/jqical.scss'
image 'jquery/jqical/calendar.png'
image 'jquery/jqical/clock.png'
