(function(){var o=tinymce.util.JSONRequest,m=tinymce.each,p=tinymce.DOM;tinymce.create("tinymce.plugins.SpellcheckerPlugin",{getInfo:function(){return{longname:"Spellchecker",author:"Moxiecode Systems AB",authorurl:"http://tinymce.moxiecode.com",infourl:"http://wiki.moxiecode.com/index.php/TinyMCE:Plugins/spellchecker",version:tinymce.majorVersion+"."+tinymce.minorVersion}},init:function(b,d){var a=this;a.url=d;a.editor=b;a.rpcUrl=b.getParam("spellchecker_rpc_url","{backend}");if(a.rpcUrl=="{backend}"){if(tinymce.isIE)return;
a.hasSupport=true;b.onContextMenu.addToTop(function(){if(a.active)return false})}b.addCommand("mceSpellCheck",function(){if(a.rpcUrl=="{backend}")a.editor.getBody().spellcheck=a.active=!a.active;else if(a.active)a._done();else{b.setProgressState(1);a._sendRPC("checkWords",[a.selectedLang,a._getWords()],function(c){if(c.length>0){a.active=1;a._markWords(c);b.setProgressState(0);b.nodeChanged()}else{b.setProgressState(0);b.getParam("spellchecker_report_no_misspellings",true)&&b.windowManager.alert("spellchecker.no_mpell")}})}});
b.settings.content_css!==false&&b.contentCSS.push(d+"/css/content.css");b.onClick.add(a._showMenu,a);b.onContextMenu.add(a._showMenu,a);b.onBeforeGetContent.add(function(){a.active&&a._removeWords()});b.onNodeChange.add(function(c,e){e.setActive("spellchecker",a.active)});b.onSetContent.add(function(){a._done()});b.onBeforeGetContent.add(function(){a._done()});b.onBeforeExecCommand.add(function(c,e){e=="mceFullScreen"&&a._done()});a.languages={};m(b.getParam("spellchecker_languages","+English=en,Danish=da,Dutch=nl,Finnish=fi,French=fr,German=de,Italian=it,Polish=pl,Portuguese=pt,Spanish=es,Swedish=sv",
"hash"),function(c,e){if(e.indexOf("+")===0){e=e.substring(1);a.selectedLang=c}a.languages[e]=c})},createControl:function(b,d){var a=this,c;if(b=="spellchecker"){if(a.rpcUrl=="{backend}"){if(a.hasSupport)c=d.createButton(b,{title:"spellchecker.desc",cmd:"mceSpellCheck",scope:a});return c}c=d.createSplitButton(b,{title:"spellchecker.desc",cmd:"mceSpellCheck",scope:a});c.onRenderMenu.add(function(e,f){f.add({title:"spellchecker.langs","class":"mceMenuItemTitle"}).setDisabled(1);m(a.languages,function(h,
g){var j={icon:1},i;j.onclick=function(){i.setSelected(1);a.selectedItem.setSelected(0);a.selectedItem=i;a.selectedLang=h};j.title=g;i=f.add(j);i.setSelected(h==a.selectedLang);if(h==a.selectedLang)a.selectedItem=i})});return c}},_walk:function(b,d){var a=this.editor.getDoc();if(a.createTreeWalker)for(a=a.createTreeWalker(b,NodeFilter.SHOW_TEXT,null,false);(b=a.nextNode())!=null;)d.call(this,b);else tinymce.walk(b,d,"childNodes")},_getSeparators:function(){var b="",d,a=this.editor.getParam("spellchecker_word_separator_chars",
'\\s!"#$%&()*+,-./:;<=>?@[]^_{|}����������������”“');for(d=0;d<a.length;d++)b+="\\"+a.charAt(d);return b},_getWords:function(){var b=this.editor,d=[],a="",c={},e=[];this._walk(b.getBody(),function(f){if(f.nodeType==3)a+=f.nodeValue+" "});if(b.getParam("spellchecker_word_pattern"))e=a.match("("+b.getParam("spellchecker_word_pattern")+")","gi");else{a=a.replace(RegExp("([0-9]|["+this._getSeparators()+"])","g")," ");a=tinymce.trim(a.replace(/(\s+)/g," "));e=a.split(" ")}m(e,function(f){if(!c[f]){d.push(f);
c[f]=1}});return d},_removeWords:function(b){var d=this.editor,a=d.dom;d=d.selection;var c=d.getBookmark();m(a.select("span").reverse(),function(e){if(e&&(a.hasClass(e,"mceItemHiddenSpellWord")||a.hasClass(e,"mceItemHidden")))if(!b||a.decode(e.innerHTML)==b)a.remove(e,1)});d.moveToBookmark(c)},_markWords:function(b){var d,a,c,e,f,h="",g=this.editor,j=this._getSeparators(),i=g.dom,k=[];g=g.selection;var q=g.getBookmark();m(b,function(n){h+=(h?"|":"")+n});d=RegExp("(["+j+"])("+h+")(["+j+"])","g");a=
RegExp("^("+h+")","g");c=RegExp("("+h+")(["+j+"]?)$","g");e=RegExp("^("+h+")(["+j+"]?)$","g");f=RegExp("("+h+")(["+j+"])","g");this._walk(this.editor.getBody(),function(n){n.nodeType==3&&k.push(n)});m(k,function(n){var l;if(n.nodeType==3){l=n.nodeValue;if(d.test(l)||a.test(l)||c.test(l)||e.test(l)){l=i.encode(l);l=l.replace(f,'<span class="mceItemHiddenSpellWord">$1</span>$2');l=l.replace(c,'<span class="mceItemHiddenSpellWord">$1</span>$2');i.replace(i.create("span",{"class":"mceItemHidden"},l),
n)}}});g.moveToBookmark(q)},_showMenu:function(b,d){var a=this;b=a.editor;var c=a._menu,e,f=b.dom,h=f.getViewPort(b.getWin()),g=d.target;d=0;if(!c){e=p.getPos(b.getContentAreaContainer());c=b.controlManager.createDropMenu("spellcheckermenu",{offset_x:e.x,offset_y:e.y,"class":"mceNoIcons"});a._menu=c}if(f.hasClass(g,"mceItemHiddenSpellWord")){c.removeAll();c.add({title:"spellchecker.wait","class":"mceMenuItemTitle"}).setDisabled(1);a._sendRPC("getSuggestions",[a.selectedLang,f.decode(g.innerHTML)],
function(j){var i;c.removeAll();if(j.length>0){c.add({title:"spellchecker.sug","class":"mceMenuItemTitle"}).setDisabled(1);m(j,function(k){c.add({title:k,onclick:function(){f.replace(b.getDoc().createTextNode(k),g);a._checkDone()}})});c.addSeparator()}else c.add({title:"spellchecker.no_sug","class":"mceMenuItemTitle"}).setDisabled(1);i=a.editor.getParam("spellchecker_enable_ignore_rpc","");c.add({title:"spellchecker.ignore_word",onclick:function(){var k=g.innerHTML;f.remove(g,1);a._checkDone();if(i){b.setProgressState(1);
a._sendRPC("ignoreWord",[a.selectedLang,k],function(){b.setProgressState(0)})}}});c.add({title:"spellchecker.ignore_words",onclick:function(){var k=g.innerHTML;a._removeWords(f.decode(k));a._checkDone();if(i){b.setProgressState(1);a._sendRPC("ignoreWords",[a.selectedLang,k],function(){b.setProgressState(0)})}}});a.editor.getParam("spellchecker_enable_learn_rpc")&&c.add({title:"spellchecker.learn_word",onclick:function(){var k=g.innerHTML;f.remove(g,1);a._checkDone();b.setProgressState(1);a._sendRPC("learnWord",
[a.selectedLang,k],function(){b.setProgressState(0)})}});c.update()});b.selection.select(g);e=f.getPos(g);c.showMenu(e.x,e.y+g.offsetHeight-h.y);return tinymce.dom.Event.cancel(d)}else c.hideMenu()},_checkDone:function(){var b=this.editor.dom,d;m(b.select("span"),function(a){if(a&&b.hasClass(a,"mceItemHiddenSpellWord")){d=true;return false}});d||this._done()},_done:function(){var b=this.active;if(this.active){this.active=0;this._removeWords();this._menu&&this._menu.hideMenu();b&&this.editor.nodeChanged()}},
_sendRPC:function(b,d,a){var c=this;o.sendRPC({url:c.rpcUrl,method:b,params:d,success:a,error:function(e,f){c.editor.setProgressState(0);c.editor.windowManager.alert(e.errstr||"Error response: "+f.responseText)}})}});tinymce.PluginManager.add("spellchecker",tinymce.plugins.SpellcheckerPlugin)})();
