# Generated by compass-jquery-plugin/gem-tasks/jrailsxx.rake
# Install with: compass -f jquery -p jrails

file 'config/initializers/jrails.rb'
javascript 'jrails.js'
javascript 'jrails.min.js'
javascript 'jquery-1.4.2.js'
javascript 'jquery-1.4.2.min.js'
javascript 'jquery.compat-1.3.js'
javascript 'jquery.compat-1.3.min.js'
javascript 'jquery.bgiframe.js'
javascript 'jquery.bgiframe.min.js'
