require 'jquery/mark_it_up'

ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup        => ['compiled/jquery/markitup/skins/markitup.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_aqua   => ['compiled/jquery/markitup/skins/aqua.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_jtag   => ['compiled/jquery/markitup/skins/jtageditor.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_live   => ['compiled/jquery/markitup/skins/live.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_simple => ['compiled/jquery/markitup/skins/simple.css']

ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_default  => ['compiled/jquery/markitup/sets/default.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_bbcode   => ['compiled/jquery/markitup/sets/bbcode.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_dotclear => ['compiled/jquery/markitup/sets/dotclear.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_html     => ['compiled/jquery/markitup/sets/html.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_markdown => ['compiled/jquery/markitup/sets/markdown.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_textile  => ['compiled/jquery/markitup/sets/textile.css']
ActionView::Helpers::AssetTagHelper.register_stylesheet_expansion :markitup_wiki     => ['compiled/jquery/markitup/sets/wiki.css']

ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup => ['jquery.markitup.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_default  => ['markitui/jquery.markitup.default.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_bbcode   => ['markitui/jquery.markitup.bbcode.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_xbbcode  => ['markitui/jquery.markitup.xbbcode.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_css      => ['markitui/jquery.markitup.css.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_dotclear => ['markitui/jquery.markitup.dotclear.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_html     => ['markitui/jquery.markitup.html.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_markdown => ['markitui/jquery.markitup.markdown.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_markmin  => ['markitui/jquery.markitup.markmin.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_rest     => ['markitui/jquery.markitup.rest.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_textile  => ['markitui/jquery.markitup.textile.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_texy     => ['markitui/jquery.markitup.texy.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_txt2tags => ['markitui/jquery.markitup.txt2tags.min']
ActionView::Helpers::AssetTagHelper.register_javascript_expansion :markitup_wiki     => ['markitui/jquery.markitup.wiki.min']
